Send error message to stderr rather than stdout.
git-svn-id: http://sipxecs.sipfoundry.org/rep/sipXecs/main@16915 ab1d8caa-1f67-47f1-9e81-24633a41865c

diff --git a/sipXcommserverLib/src/sipx-utils.sh.in b/sipXcommserverLib/src/sipx-utils.sh.in
--- a/sipXcommserverLib/src/sipx-utils.sh.in
+++ b/sipXcommserverLib/src/sipx-utils.sh.in
@@ -44,7 +44,7 @@ then
   HTTP_DAEMON_START="start-stop-daemon --start --chuid root --exec @APACHE2_HTTPD@ --"
 
 else
-  # Other distos
+  # Other distros
   echo_success()
   {
       echo success
@@ -67,7 +67,7 @@ sipx_config_exists() { # ( CONFIG-FILE )
     local exists=0
     if ! test -f "$1"
     then
-        echo "Configuration file not found: '$1'"
+        echo "Configuration file not found: '$1'" >&2
         exists=1
     fi
     return ${exists}
