[XECS-1482] sipxpbx startup script configtest improvements    Remove running configtest in script at start time    Reduce chattyness of call resolver config test    Create common test for existance of a config file, with error message    Clean up sipXivr configtest, check for sipxivr.properties    Add checks for status server configuration files    Clean up existance tests and message indenting
git-svn-id: http://sipxecs.sipfoundry.org/rep/sipXecs/main@13510 ab1d8caa-1f67-47f1-9e81-24633a41865c

diff --git a/sipXcommserverLib/src/sipx-utils.sh.in b/sipXcommserverLib/src/sipx-utils.sh.in
--- a/sipXcommserverLib/src/sipx-utils.sh.in
+++ b/sipXcommserverLib/src/sipx-utils.sh.in
@@ -151,10 +151,21 @@ sipx_system_is_master() {
     fi
 }
 
+sipx_config_exists() { # ( CONFIG-FILE )
+    local exists=0
+    if ! test -f "$1"
+    then 
+        echo "Configuration file not found: '$1'" 1>&2
+        exists=1
+    fi
+    return ${exists}
+}
+
 sipx_config_value() { # ( CONFIG-FILE, DIRECTIVE )
 #   prints the value of DIRECTIVE from CONFIG-FILE
 #   list values have any commas removed
-    perl -n \
+    sipx_config_exists "$1" \
+    && perl -n \
         -e 'use English;' \
         -e 's/#.*$//;' \
         -e "/^\\s*$2\\s*:\\s*/ && print join( ' ', split( /[\\s,]+/, \$POSTMATCH ));" \
