Allow check-cert.sh to check multiple certificates Improve error reporting
git-svn-id: http://sipxecs.sipfoundry.org/rep/sipXecs/main@12943 ab1d8caa-1f67-47f1-9e81-24633a41865c

diff --git a/sipXcommserverLib/bin/ssl-cert/check-cert.sh.in b/sipXcommserverLib/bin/ssl-cert/check-cert.sh.in
--- a/sipXcommserverLib/bin/ssl-cert/check-cert.sh.in
+++ b/sipXcommserverLib/bin/ssl-cert/check-cert.sh.in
@@ -10,6 +10,9 @@ ExpireWarn=30
 ExpireFail=0
 Names=""
 CAdir=@SIPX_CONFDIR@/ssl/authorities
+openssl=@OPENSSL@
+Certificates=""
+FailedCerts=""
 
 while [ $# -ne 0 ]
 do
@@ -87,21 +90,14 @@ do
             ;;
 
         *)
-            if [ -z "${Certificate}" ]
-            then
-                Certificate=${1}
-            else
-                echo "Too many arguments supplied: $@" 1>&2
-                Action=USAGE
-                break
-            fi
+            Certificates="${Certificates} ${1}"
             ;;
     esac           
 
     shift # always consume 1
 done
 
-if [ "${Action}" = "USAGE" -o -z "${Certificate}" ]
+if [ "${Action}" = "USAGE" -o -z "${Certificates}" ]
 then
     cat <<USAGE
 
@@ -112,17 +108,17 @@ Usage:
                [ {-f | --fail} <failure-days> ]
                [ {-n | --name} <name> ]...
                [ {-a | --authority} <authority-file> ]...
-               <certificate-file>
+               <certificate-file> ...
 
-    Checks signature validity, name, and expiration of certificate.
+    Checks signature validity, name, and expiration of each certificate.
 
-    Prints a warning if the certificate will expire
+    Prints a warning if a certificate will expire
       in less than <warning-days> (default is 30)
 
-    Returns failure (and prints message) if the certificate expires 
+    Returns failure (and prints message) if a certificate expires 
       in less than <failure-days> (default is 0)
 
-    Always returns a failure if the certificate has expired.
+    Always returns a failure if any certificate has expired.
     
     The --name option may be repeated any number of times, and if it is
     given, the commonName attribute of the certificate must equal one of
@@ -160,37 +156,53 @@ then
      Authority certificate: "${Authority}"
 EOF
     ExitStatus=1
+    FailedCerts="${Certificates}"
 fi
 
-if [ -r "${Certificate}" ]
-then
-    
+numCertsTested=0
+for Certificate in ${Certificates}
+do
+    numCertsTested+=1
+
     # Validate the signatures and issuers
     #   (also checks expiration, but does not provide advance warning as below)
-    cat /dev/null > /tmp/check-cert.$$
-    @OPENSSL@ verify ${AuthSwitch} "${AuthTarget}" -purpose sslclient \
-         "${Certificate}" \
-         > /tmp/check-cert.$$ 2>&1
-    if ! echo "${Certificate}: OK" | diff - /tmp/check-cert.$$ > /dev/null 2>&1
-    then
-        echo "SSL Certificate '${Certificate}' is invalid as client certificate." 1>&2
-        sed 's/^/    /' /tmp/check-cert.$$ 1>&2
-        ExitStatus=1
-    fi
-    cat /dev/null > /tmp/check-cert.$$
-    @OPENSSL@ verify ${AuthSwitch} "${AuthTarget}" -purpose sslserver \
-         "${Certificate}" \
-         > /tmp/check-cert.$$ 2>&1
-    if ! echo "${Certificate}: OK" | diff - /tmp/check-cert.$$ > /dev/null 2>&1
-    then
-        echo "SSL Certificate '${Certificate}' is invalid as server certificate." 1>&2
-        sed 's/^/    /' /tmp/check-cert.$$ 1>&2
-        ExitStatus=1
-    fi
-    rm -f /tmp/check-cert.$$
+    CheckFile=`mktemp -t check-cert.XXXXXX`
+    trap "rm -f ${CheckFile} > /dev/null 2>&1" 0
+    cat /dev/null > ${CheckFile}
+
+    case ${Certificate} in
+        *-sip.*)
+            # do not check for web usages on a sip certificate
+            ;;
+        *)
+            ${openssl} verify ${AuthSwitch} "${AuthTarget}" -purpose sslclient \
+                "${Certificate}" \
+                > ${CheckFile} 2>&1
+            if ! echo "${Certificate}: OK" | diff - ${CheckFile} > /dev/null 2>&1
+            then
+                echo "SSL Certificate '${Certificate}' is invalid as client certificate." 1>&2
+                sed 's/^/    /' ${CheckFile} 1>&2
+                ExitStatus=1
+                FailedCerts="${FailedCerts} ${Certificate}"
+            fi
+            cat /dev/null > ${CheckFile}
+            ${openssl} verify ${AuthSwitch} "${AuthTarget}" -purpose sslserver \
+                "${Certificate}" \
+                > ${CheckFile} 2>&1
+            if ! echo "${Certificate}: OK" | diff - ${CheckFile} > /dev/null 2>&1
+            then
+                echo "SSL Certificate '${Certificate}' is invalid as server certificate." 1>&2
+                sed 's/^/    /' ${CheckFile} 1>&2
+                ExitStatus=1
+                FailedCerts="${FailedCerts} ${Certificate}"
+            fi
+            ;;
+    esac
+
+    rm -f ${CheckFile}
 
     # Check subject name if any correct answers are provided
-    cert_name=`@OPENSSL@ x509 -in "${Certificate}" -subject -nameopt RFC2253,multiline -noout \
+    cert_name=`${openssl} x509 -in "${Certificate}" -subject -nameopt RFC2253,multiline -noout \
                | perl -ne 'use English; m/^ +commonName += / && print $POSTMATCH' \
                | tr A-Z a-z
                `
@@ -204,10 +216,11 @@ then
         done
         if [ "${Matched}" = "NO" ]
         then
-            echo -n "SSL certificate name '${cert_name}' is not one of: " 1>&2
+            echo -n "SSL certificate '${Certificate}' name '${cert_name}' is not one of: " 1>&2
             for name in ${UniqueNames}; do echo -n "'${name}' " 1>&2; done
             echo "" 1>&2
             ExitStatus=1
+            FailedCerts="${FailedCerts} ${Certificate}"
             ShowCert="SHOW"
         fi
     fi
@@ -216,7 +229,7 @@ then
     warnSeconds=$((${ExpireWarn} * 3600 * 24))
     failSeconds=$((${ExpireFail} * 3600 * 24))
 
-    cert_expires=`@OPENSSL@ x509 -in "${Certificate}" -noout -enddate | sed 's/notAfter=//'`
+    cert_expires=`${openssl} x509 -in "${Certificate}" -noout -enddate | sed 's/notAfter=//'`
     now=`date +%s`
     if [ $? -eq 0 ] # date command support epoch format
     then
@@ -228,49 +241,62 @@ then
 
             if [ ${remaining} -le 0 ] # cert expired
             then
-                echo "SSL certificate expired: ${cert_expires}" 1>&2
+                echo "SSL certificate '${Certificate}' expired: ${cert_expires}" 1>&2
                 ExitStatus=1
+                FailedCerts="${FailedCerts} ${Certificate}"
+
             elif [ ${failSeconds} -gt 0 -a ${remaining} -le ${failSeconds} ]
             then
-                echo "SSL certificate expires in less than ${ExpireFail} days: ${cert_expires}" 1>&2
+                echo "SSL certificate '${Certificate}' expires in less than ${ExpireFail} days: ${cert_expires}" 1>&2
                 ExitStatus=1
+                FailedCerts="${FailedCerts} ${Certificate}"
+
             elif [ ${remaining} -le ${warnSeconds} ]
             then
-                echo "SSL certificate expires in less than ${ExpireWarn} days: ${cert_expires}" 1>&2
+                echo "SSL certificate '${Certificate}' expires in less than ${ExpireWarn} days: ${cert_expires}" 1>&2
                 ShowCert="SHOW"
             fi
         else
             echo "Your 'date' command does not support %s format - cannot calculate expiration." 1>&2
-            echo "SSL certificate expires: ${cert_expires}" 1>&2
+            echo "SSL certificate '${Certificate}' expires: ${cert_expires}" 1>&2
             ShowCert="SHOW"
         fi
         else
         echo "Your 'date' command does not support %s format - cannot calculate expiration." 1>&2
-        echo "SSL certificate expires: ${cert_expires}" 1>&2
+        echo "SSL certificate '${Certificate}' expires: ${cert_expires}" 1>&2
         ShowCert="SHOW"
     fi
 
     if [ "${Feedback}" = "VERBOSE" ]
     then
-        caName=`@OPENSSL@ x509 -in "${Certificate}" -issuer -nameopt RFC2253,multiline -noout | perl -ne 'use English; m/^ +commonName += / && print $POSTMATCH'`
+        caName=`${openssl} x509 -in "${Certificate}" -issuer -nameopt RFC2253,multiline -noout \
+            | perl -ne 'use English; m/^ +commonName += / && print $POSTMATCH'`
 
-        echo "SSL certificate name:    ${cert_name}" 
-        echo "SSL certificate issuer:  ${caName}" 
-        echo "SSL certificate expires: ${cert_expires}" 
+        echo "SSL certificate '${Certificate}' name:    ${cert_name}" 
+        echo "SSL certificate '${Certificate}' issuer:  ${caName}" 
+        echo "SSL certificate '${Certificate}' expires: ${cert_expires}" 
     fi
 
-else
-    echo "SSL certificate not found." 1>&2
+done
+
+if [ ${numCertsTested} -eq 0 ]
+then
+    echo "No SSL certificate found." 1>&2
     ExitStatus=1
 fi
 
 if [ ${ExitStatus} -ne 0 -o "${ShowCert}" = "SHOW" ]
 then
-    echo "SSL certificate: ${Certificate}" 1>&2
+    echo "SSL certificates: ${Certificates}" 1>&2
+fi
+
+if [ ${ExitStatus} -ne 0 ]
+then
+    echo "Check failed for ${FailedCerts}" 1>&2
 fi
 
 exit ${ExitStatus}
-# DUMP x509v3 = @OPENSSL@ x509 -in /opt/ssl-sipit/ssl.crt -text -certopt ca_default -certopt no_sigdump -certopt no_validity -certopt no_serial -certopt no_subject -certopt no_signame -noout
+# DUMP x509v3 = openssl x509 -in /opt/ssl-sipit/ssl.crt -text -certopt ca_default -certopt no_sigdump -certopt no_validity -certopt no_serial -certopt no_subject -certopt no_signame -noout
 #         X509v3 extensions:
 #             X509v3 Basic Constraints: 
 #             CA:FALSE
