XX-10707 Service restart reports as failed although it restarted fine
-modified maxTimeout from 10 to 25
-added new default timeout for listen on port with value 50
-waitForListenPortTime in sipXconfig is now set from 20 to 60

-modified 'start' function to receive an extra argument.
 If an extra argument is provided then after launching we check in the process table
 and if listening on a port.
 If no extra argument is provided then the process is launched with no checks or minimal
 checks

-added asyncrestart function which calls 'stop' and 'start' without timeout

-modified cfengine scripts to call asyncrestart instead of restart

-modified sipXsbc and sipXhomer cfengine scripts and init scripts

diff --git a/sipXsaa/bin/sipxsaa.in b/sipXsaa/bin/sipxsaa.in
--- a/sipXsaa/bin/sipxsaa.in
+++ b/sipXsaa/bin/sipxsaa.in
@@ -28,19 +28,25 @@ start() {
   else
     checkRunningInstance @SIPXPBXUSER@ $prog > /dev/null
     Status=$?
-    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }     
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
     
     echo -n $"Starting $prog: "
     daemon --user @SIPXPBXUSER@ --pidfile $pidfile $exec $pidfile
-    
-    #check if process was spawned
-    checkRunningInstanceTimeout @SIPXPBXUSER@ $prog
     Status=$?
-    [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
-    checkIfListening $prog
-    Status=$?
-    [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
-    [ $Status -eq 0 ] && { echo_success; echo; }
+
+    if [ $# -gt 0 ]; then
+      #check if process was spawned
+      checkRunningInstanceTimeout @SIPXPBXUSER@ $prog
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+      checkIfListening $prog
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; echo; }
+    else
+      [ $Status -eq 0 ] && { echo_success; echo; }
+      [ $Status -eq 0 ] || { echo_failure; echo; }
+    fi
   fi
 }
 
@@ -55,6 +61,11 @@ stop() {
 
 restart() {
   stop
+  start $withCheck
+}
+
+asyncrestart() {
+  stop
   start
 }
 
@@ -64,13 +75,16 @@ case "$1" in
     start
     ;;
   start)
-    start
+    start $withCheck
     ;;
   stop)
     stop
     ;;
   restart|reload|force-reload)
     restart
+    ;;
+  asyncrestart)
+    asyncrestart
     ;;
   condrestart)
     checkRunningInstance @SIPXPBXUSER@ $prog > /dev/null
@@ -84,8 +98,9 @@ case "$1" in
   configtest)
     ;;
   *)
-    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|nofork}"
+    echo "Usage: $0 {start|stop|status|restart|asyncrestart|reload|force-reload|condrestart|nofork}"
     Status=1
 esac
 
 exit $Status
+
