Install the merged-proxy change into main. XECS-481
Merged revisions 11103-11171,11268,11276-11277,11281,11292,11282,11221 via svnmerge from 
https://sipxecs.sipfoundry.org/rep/sipXecs/branches/user_dworley_main_mp_merge

  r11104 | dworley | 2007-10-29 22:01:51 -0400 (Mon, 29 Oct 2007) | 4 lines
  r11129 | dworley | 2007-11-01 15:38:14 -0400 (Thu, 01 Nov 2007) | 8 lines
  r11130 | dworley | 2007-11-01 16:36:15 -0400 (Thu, 01 Nov 2007) | 5 lines
  r11134 | dworley | 2007-11-02 07:43:55 -0400 (Fri, 02 Nov 2007) | 10 lines
  r11139 | dworley | 2007-11-02 14:48:43 -0400 (Fri, 02 Nov 2007) | 10 lines
  r11142 | dworley | 2007-11-02 17:50:43 -0400 (Fri, 02 Nov 2007) | 8 lines
  r11143 | dworley | 2007-11-02 18:19:43 -0400 (Fri, 02 Nov 2007) | 7 lines
  r11144 | dworley | 2007-11-02 19:33:22 -0400 (Fri, 02 Nov 2007) | 2 lines
  r11147 | dworley | 2007-11-02 20:00:32 -0400 (Fri, 02 Nov 2007) | 2 lines
  r11171 | dworley | 2007-11-05 16:22:21 -0500 (Mon, 05 Nov 2007) | 3 lines
  r11268 | dworley | 2007-11-14 16:55:03 -0500 (Wed, 14 Nov 2007) | 3 lines
  r11276 | dworley | 2007-11-15 15:15:32 -0500 (Thu, 15 Nov 2007) | 11 lines
  r11277 | dworley | 2007-11-15 15:25:40 -0500 (Thu, 15 Nov 2007) | 3 lines
  r11281 | dworley | 2007-11-15 18:24:14 -0500 (Thu, 15 Nov 2007) | 3 lines
  r11292 | dworley | 2007-11-16 18:22:15 -0500 (Fri, 16 Nov 2007) | 4 lines
  r11282 | dworley | 2007-11-15 19:33:33 -0500 (Thu, 15 Nov 2007) | 21 lines
  r11221 | dworley | 2007-11-09 16:51:57 -0500 (Fri, 09 Nov 2007) | 31 lines


git-svn-id: http://sipxecs.sipfoundry.org/rep/sipXecs/main@11345 ab1d8caa-1f67-47f1-9e81-24633a41865c

diff --git a/sipXproxy/etc/Makefile.am b/sipXproxy/etc/Makefile.am
--- a/sipXproxy/etc/Makefile.am
+++ b/sipXproxy/etc/Makefile.am
@@ -3,22 +3,19 @@ include $(top_srcdir)/config/subdir.am
 SUBDIRS = database
 
 cfgfiles_IN = \
-    authproxy-config.in \
-    authrules.xml.in \
-    callresolver-config.in \
-    proxy-config.in \
-    forwardingrules.xml.in
+	authrules.xml.in \
+	callresolver-config.in \
+	sipXproxy-config.in \
+	forwardingrules.xml.in
 
 EXTRA_DIST = \
-    sipproxy.process.xml.in \
-    sipauthproxy.process.xml.in \
-    sipxcallresolver.process.xml.in \
-    authproxy-config.in.map \
-    $(cfgfiles_IN)
+	sipXproxy.process.xml.in \
+	sipxcallresolver.process.xml.in \
+	sipXproxy-config.in.map \
+	$(cfgfiles_IN)
 
 PROCESS_XML_FILES = \
-	$(DESTDIR)$(SIPX_PROCDIR)/sipproxy.process.xml \
-	$(DESTDIR)$(SIPX_PROCDIR)/sipauthproxy.process.xml
+	$(DESTDIR)$(SIPX_PROCDIR)/sipXproxy.process.xml
 
 if ENABLE_CDR
 PROCESS_XML_FILES += \
@@ -31,14 +28,15 @@ install-exec-hook : \
 	upgrade-add-domain \
 	upgrade-auth-rules \
 	upgrade-forwarding-rules \
-	upgrade-auth-plugins
+	upgrade-auth-plugins \
+	upgrade-to-merged-proxy
 
 install-data-hook : \
-	$(DESTDIR)$(sysconfdir)/sipxpbx/authproxy-config.in.map \
+	$(DESTDIR)$(sysconfdir)/sipxpbx/sipXproxy-config.in.map \
 	$(PROCESS_XML_FILES)
 
-$(DESTDIR)$(sysconfdir)/sipxpbx/authproxy-config.in.map: authproxy-config.in.map
-	  echo ""; echo "Installing authproxy-config.in.map $@"; \
+$(DESTDIR)$(sysconfdir)/sipxpbx/sipXproxy-config.in.map: sipXproxy-config.in.map
+	  echo ""; echo "Installing sipXproxy-config.in.map $@"; \
 	  $(INSTALL) -D -m 644 $< $@; 
 
 $(foreach file,$(cfgfiles_IN),$(DESTDIR)/$(sysconfdir)/sipxpbx/$(file)) : $(DESTDIR)/$(sysconfdir)/sipxpbx/% : %.local
@@ -72,23 +70,23 @@ upgrade-forwarding-rules:
 
 .PHONY: upgrade-auth-plugins
 upgrade-auth-plugins :
-	@echo -n "        Checking for authproxy plugins..."
-	@if ! grep libEnforceAuthRules.so $(DESTDIR)$(sysconfdir)/sipxpbx/authproxy-config.in > /dev/null 2>&1 ; \
+	@echo -n "        Checking for auth plugins..."
+	@if ! grep libEnforceAuthRules.so $(DESTDIR)$(sysconfdir)/sipxpbx/sipXproxy-config.in > /dev/null 2>&1 ; \
 	then \
 		echo -n " 'authrules' added"; \
 		( echo "" \
-		; echo "SIP_AUTHPROXY_HOOK_LIBRARY.authrules : $(libdir)/sipxauthproxy/libEnforceAuthRules.so" \
-		; echo "SIP_AUTHPROXY.authrules.RULES        : $(sysconfdir)/sipxpbx/authrules.xml" \
-		) >> $(DESTDIR)$(sysconfdir)/sipxpbx/authproxy-config.in; \
+		; echo "SIPX_PROXY_HOOK_LIBRARY.authrules : $(libdir)/authplugins/libEnforceAuthRules.so" \
+		; echo "SIPX_PROXY.authrules.RULES        : $(sysconfdir)/sipxpbx/authrules.xml" \
+		) >> $(DESTDIR)$(sysconfdir)/sipxpbx/sipXproxy-config.in; \
 	else \
 		echo -n " 'authrules' ok"; \
 	fi; \
-	if ! grep libCallerAlias.so $(DESTDIR)$(sysconfdir)/sipxpbx/authproxy-config.in > /dev/null 2>&1 ; \
+	if ! grep libCallerAlias.so $(DESTDIR)$(sysconfdir)/sipxpbx/sipXproxy-config.in > /dev/null 2>&1 ; \
 	then \
 		echo -n " 'fromalias' added"; \
 		( echo "" \
-		; echo "SIP_AUTHPROXY_HOOK_LIBRARY.fromalias : $(libdir)/sipxauthproxy/libCallerAlias.so" \
-		) >> $(DESTDIR)$(sysconfdir)/sipxpbx/authproxy-config.in; \
+		; echo "SIPX_PROXY_HOOK_LIBRARY.fromalias : $(libdir)/authplugins/libCallerAlias.so" \
+		) >> $(DESTDIR)$(sysconfdir)/sipxpbx/sipXproxy-config.in; \
 	else \
 		echo -n " 'fromalias' ok"; \
 	fi
@@ -98,13 +96,25 @@ upgrade-auth-plugins :
 .PHONY: upgrade-add-domain
 upgrade-add-domain :
 	@echo -n "        Checking for domain configuration..."
-	@if ! grep -e '^SIP_AUTHPROXY_DOMAIN_NAME\>' $(DESTDIR)$(sysconfdir)/sipxpbx/authproxy-config.in > /dev/null 2>&1 ; \
+	@if ! grep -e '^SIPX_PROXY_DOMAIN_NAME\>' $(DESTDIR)$(sysconfdir)/sipxpbx/sipXproxy-config.in > /dev/null 2>&1 ; \
 	then \
 		echo " adding "; \
 		( echo "" \
-		; echo 'SIP_AUTHPROXY_DOMAIN_NAME : $${SIPXCHANGE_DOMAIN_NAME}' \
-		) >> $(DESTDIR)$(sysconfdir)/sipxpbx/authproxy-config.in; \
+		; echo 'SIPX_PROXY_DOMAIN_NAME : $${SIPXCHANGE_DOMAIN_NAME}' \
+		) >> $(DESTDIR)$(sysconfdir)/sipxpbx/sipXproxy-config.in; \
 	else \
 		echo " ok"; \
 	fi
+
+.PHONY: upgrade-to-merged-proxy
+upgrade-to-merged-proxy :
+	@echo -n "        Checking for deprecated forking and auth proxy leftovers  => "
+	@if [ -f $(DESTDIR)$(sysconfdir)/sipxpbx/proxy-config.in ] && [ -f $(DESTDIR)$(sysconfdir)/sipxpbx/authproxy-config.in ]; \
+	then \
+		$(DESTDIR)$(bindir)/upgrade2mergedproxy --preserve --cleancfgin --cleanlogs --cleanproc --cdir $(DESTDIR)$(sysconfdir)/sipxpbx --ldir $(DESTDIR)$(localstatedir)/log/sipxpbx; \
+		echo "  [CLEANED]";\
+	else \
+		echo "  [NOT FOUND]";\
+	fi;
+
 
