Properly search for where Freeswitch is installed. Give start-up error if Freeswitch binary is not found.
git-svn-id: http://sipxecs.sipfoundry.org/rep/sipXecs/main@15371 ab1d8caa-1f67-47f1-9e81-24633a41865c

diff --git a/sipXfreeSwitch/bin/freeswitch.sh.in b/sipXfreeSwitch/bin/freeswitch.sh.in
--- a/sipXfreeSwitch/bin/freeswitch.sh.in
+++ b/sipXfreeSwitch/bin/freeswitch.sh.in
@@ -10,6 +10,8 @@ Action=RUN
 Status=0
 Args=""
 
+. @SIPX_LIBEXECDIR@/sipx-utils.sh
+
 iam=`whoami`
 
 while [ $# -ne 0 ]
@@ -90,15 +92,21 @@ case ${Action} in
            @SIPX_LIBEXECDIR@/setup.d/freeswitch_setup.sh
         else
            Status=1
-           echo -e "\n Invalid FreeSWITCH folders & files permissions, run 'freeswitch.sh --configtest' as root to fix this \n"
+           echo -e "\n Invalid FreeSWITCH folders & files permissions, run 'freeswitch.sh --configtest' as root to fix this \n" >&2
         fi  
      fi
+
      # check validity of xml routing rules
 #     @SIPX_BINDIR@/sipx-validate-xml @FREESWITCH_PREFIX@/conf/freeswitch.xml
-#     Status=$?
+#     Status=$((${Status} + $?))
+
+     if [ ! -x @FREESWITCH_PREFIX@/bin/freeswitch ]
+     then
+	 echo "Error: FreeSWITCH executable is not at @FREESWITCH_PREFIX@/bin/freeswitch" >&2
+	 Status=$((${Status} + 1))
+     fi
 
      ;;
 esac
 
 exit $Status
-
diff --git a/sipXproxy/bin/sipxcallresolver.sh.in b/sipXproxy/bin/sipxcallresolver.sh.in
--- a/sipXproxy/bin/sipxcallresolver.sh.in
+++ b/sipXproxy/bin/sipxcallresolver.sh.in
@@ -52,7 +52,7 @@ PsqlCmd="${Psql} --quiet --tuples-only --no-align --username ${PgUser} --dbname 
 assertRoot() {
     user=`whoami`
     if [ "${user}" != "root" ]; then
-      echo_error "Error: Must be root to run sipxcallresolver.sh script."
+      echo "Error: Must be root to run sipxcallresolver.sh script." >&2
       exit 1
     fi
 }
