fix sipXvxml.sh --configtest and print why it fails if it does, reclassify voicemail.xml resource correctly
git-svn-id: http://sipxecs.sipfoundry.org/rep/sipXecs/main@15070 ab1d8caa-1f67-47f1-9e81-24633a41865c

diff --git a/sipXvxml/bin/sipXvxml.sh.in b/sipXvxml/bin/sipXvxml.sh.in
--- a/sipXvxml/bin/sipXvxml.sh.in
+++ b/sipXvxml/bin/sipXvxml.sh.in
@@ -74,10 +74,13 @@ case ${Action} in
      ;;
 
    CONFIGTEST)
-     test -c @SIPX_CONFDIR@/voicemail.xml
-     Status=$?
-     #@bindir@/sipx-validate-xml @SIPX_CONFDIR@/?.xml
-     #Status=$(($Status+$?))
+     if test -r @SIPX_CONFDIR@/voicemail.xml
+     then
+         Status=0
+     else
+         echo "Missing @SIPX_CONFDIR@/voicemail.xml" 1>&2
+         Status=1
+     fi
      ;;
 
    STOP)
