XECS-227 remove remaining references to config.defs config-defs and configpp
git-svn-id: http://sipxecs.sipfoundry.org/rep/sipXecs/main@15063 ab1d8caa-1f67-47f1-9e81-24633a41865c

diff --git a/sipXpbx/bin/sipx-test-ssl.in b/sipXpbx/bin/sipx-test-ssl.in
--- a/sipXpbx/bin/sipx-test-ssl.in
+++ b/sipXpbx/bin/sipx-test-ssl.in
@@ -7,7 +7,7 @@
 Status=0
 
 # Source configuration
-. @SIPX_CONFDIR@/config.defs
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || exit 1
 
 if ! [ -e @SIPX_CONFDIR@/ssl/ssl.key -a -e @SIPX_CONFDIR@/ssl/ssl.crt ]; then
         cat <<EOF
@@ -20,13 +20,20 @@ if ! [ -e @SIPX_CONFDIR@/ssl/ssl.key -a -e @SIPX_CONFDIR@/ssl/ssl.crt ]; then
 EOF
         Status=1
 else
-        ## rehash certificate authorities certificates - if this fails, it will be caught below
-        @bindir@/ssl-cert/ca_rehash > /dev/null 2>&1
+    ## rehash certificate authorities certificates - if this fails, it will be caught below
+    @bindir@/ssl-cert/ca_rehash > /dev/null 2>&1
 
+    domain=`sipx_config_value @SIPX_CONFDIR@/domain-config SIP_DOMAIN_NAME`
+    if [ -n "${domain}" ]
+    then
         ## check certificate
         @bindir@/ssl-cert/check-cert.sh \
-            --name ${SIPXCHANGE_DOMAIN_NAME} --name ${MY_FULL_HOSTNAME} \
+            --name ${domain} --name `hostname -f` \
             --fail 5 @SIPX_CONFDIR@/ssl/ssl.crt
         Status=$?
+    else
+        echo "    No SIP_DOMAIN_NAME set in @SIPX_CONFDIR@/domain-config"
+        Status=1
+    fi
 fi
 exit $Status
diff --git a/sipXpbx/sipXdialog/bin/sipxdialog.sh.in b/sipXpbx/sipXdialog/bin/sipxdialog.sh.in
--- a/sipXpbx/sipXdialog/bin/sipxdialog.sh.in
+++ b/sipXpbx/sipXdialog/bin/sipxdialog.sh.in
@@ -23,25 +23,6 @@ do
     shift # always consume 1
 done
 
-CONFIG_DEFS="@SIPX_CONFDIR@/config.defs"
-
-CONFIG_FILES="\
-  @SIPX_CONFDIR@/sipxdialog-config \
-  "
-
-# If the "config.defs" file exists and the <name>.in file exists for a
-# configuration file, then run the config preprocessor to generate the
-# fully resolved configuration file.
-if [ -f "$CONFIG_DEFS" ]
-then
-  for i in $CONFIG_FILES ; do
-    if [ -f "${i}.in" ]
-    then
-       @bindir@/configpp --defs "${CONFIG_DEFS}" --in "${i}.in" --out "$i"
-    fi
-  done
-fi
-
 case ${Action} in
    RUN)
      echo $$ > @SIPX_RUNDIR@/sipxdialog.pid
@@ -51,6 +32,11 @@ case ${Action} in
    CONFIGTEST)
      Status=0
 
+     if [ ! -e "@SIPX_CONFDIR@/sipxdialog-config" ]
+     then
+         echo "Missing configuration file '@SIPX_CONFDIR@/sipxdialog-config'" 1>&2
+         Status=1
+     fi
      #@bindir@/sipx-validate-xml @SIPX_CONFDIR@/sipxdialog-config.xml
      #Status=$(($Status+$?))
 
