XX-7870 added some sanity checks to the restore script Sanity checking for the moment does the following: for configuration archive: checks if db.tar is present. If not this is not a good archive - an error message is thrown for voicemail archive: checks if db.tar is present. It it is, this is definitely a configuration archive.
Note that this sanity checks only prevent switching the configuration and voicemail archive. Trying to restore a voicemail archive
as configuration will render the application useless.

Further sanity checks should be added as improvements.


git-svn-id: http://sipxecs.sipfoundry.org/rep/sipXecs/main@18530 ab1d8caa-1f67-47f1-9e81-24633a41865c

diff --git a/sipXpbx/bin/sipx-restore.in b/sipXpbx/bin/sipx-restore.in
--- a/sipXpbx/bin/sipx-restore.in
+++ b/sipXpbx/bin/sipx-restore.in
@@ -180,6 +180,19 @@ then
   fi
 fi
 
+#sanity check - we check if configuration/voicemail archives are indeed configuration/voicemail files respectively
+if [[ `tar --list --file=$CONFIGURATION_PATH | grep db.tar` != db.tar ]];
+then
+  echo "Configuration archive seems invalid (it's either corrupt or incomplete, or it may be a voicemail archive)"
+  exit 7
+fi
+
+if [[ `tar --list --file=$VOICEMAIL_PATH | grep db.tar` = db.tar ]];
+then
+  echo "Voicemail archive seems invalid (it looks like a configuration archive)"
+  exit 8
+fi
+
 if [ $CHECK_ARCHIVE = "yes" ]
 then
   echo "Archive seems to be O.K. You can proceed with restoring"
