Try harder to shutdown processes--complain louder if they won't.
After sending SIGTERM, it now waits up to 20 seconds for the process to exit.

After that, it sends SIGABRT (in an attempt to get a core dump), and waits
up to 60 seconds for the process to exit.

After that, it sends SIGKILL, and waits up to 60 more seconds.

If the darn thing is still alive after all that, a warning is displayed.

Here is what it looks like:
$ /etc/init.d/sipxpbx stop
Stopping sipXpbx: 
  Stopping: watchdog 
  Stopping: keepalive 
...
  Confirm Stop: watchdog                                   [  OK  ]
  Confirm Stop: keepalive                                  [  OK  ]
...
  Confirm Stop: sipxacd ....................
    sipxacd did not Stop.
    Trying to abort sipxacd  55 50 45 40 35 30 25 20 15 10 5 0
    sipxacd did not abort.
    Trying to kill sipxacd  55 50 45 40 35 30 25 20 15 10 5 0
                                                           [FAILED]
    sipxacd will not die.
    Machine must be restarted!
  Confirm Stop: sipxcallresolver                           [  OK  ]
...

The "OK" is in the color green on capable terminals, while the "FAILED" and 
restart message are in the color red.

Fixes XECS-113 - Shutting down processes that do not shut down promptly has 
several problems (esp. no core dump taken)

--Woof!


git-svn-id: http://sipxecs.sipfoundry.org/rep/sipXecs/main@10250 ab1d8caa-1f67-47f1-9e81-24633a41865c

diff --git a/sipXpbx/bin/sipxpbx.in b/sipXpbx/bin/sipxpbx.in
--- a/sipXpbx/bin/sipxpbx.in
+++ b/sipXpbx/bin/sipxpbx.in
@@ -243,43 +243,65 @@ stopCheck() {
 
    STATUS=0
 
+   echo -n "  Confirm Stop: $proc_name "
    pidFile=@SIPX_RUNDIR@/$proc_name.pid
    if [ -r ${pidFile} ]
    then
-       echo -n "  Confirm Stop: $proc_name "
        PID=`cat ${pidFile} 2> /dev/null`
-
        if [ `proc_alive $PID` -eq 0 ]
        then
-          for ticks in 3 2 1 0 
+          for ticks in `seq 19 -1 0`
           do
              sleep 1
              test `proc_alive $PID` -eq 0 && echo -n "." || break
           done
           if [ `proc_alive $PID` -eq 0 ]
           then
-              kill -9 $PID 2> /dev/null
-              for ticks in 3 2 1 0 
+              # It didn't die!  Try to get a core dump
+              echo ""
+              echo    "    $proc_name did not Stop."
+              echo -n "    Trying to abort $proc_name "
+              kill -ABRT $PID 2> /dev/null
+              for ticks in `seq 55 -5 0`
               do
-                 sleep 1
-                 test `proc_alive $PID` -eq 0 && echo -n "." || break
+                 sleep 5
+                 test `proc_alive $PID` -eq 0 && echo -n " $ticks" || break
               done
+              if [ `proc_alive $PID` -eq 0 ]
+              then
+                  echo ""
+                  echo    "    $proc_name did not abort."
+                  echo -n "    Trying to kill $proc_name "
+                  kill -KILL $PID 2> /dev/null
+                  for ticks in `seq 55 -5 0`
+                  do
+                     sleep 5
+                     test `proc_alive $PID` -eq 0 && echo -n " $ticks" || break
+                  done
+              fi
           fi
        fi
           
        if [ `proc_alive $PID` -eq 0 ]
        then
+           # Holy fluff!  It didn't die!  The end is nigh!
+           echo ""
            echo_failure
            echo ""
+           [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
+           echo "    $proc_name will not die."
+           echo "    Machine must be restarted!"
+           [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
        else
            echo_success
            echo ""
+           rm -f ${pidFile}
        fi
 
-       rm -f ${pidFile}
    else
-       echo -n "no record found for '${proc_name}'"
-       echo_failure
+       echo -n "(Not started) "
+       echo_success
+       echo ""
    fi
 }
 
@@ -333,9 +355,6 @@ stop_sipx () {
     do
         stopCheck $process
     done
-    
-    echo_success
-    echo
 }
 
 check_rpmnew() {
