UC-647 Improve init scripts http://track.sipfoundry.org/browse/UC-647 - output of scripts ends with a newline - when stop is called processes are now killed by name - to see if a process was launched successfully we :     -look for the pid of the new spawned process in the process table     for a maximum amount of time     -check to see if the process is listening on a port (netstat is used) - before printing echo_succsess or echo_failure return codes are analyzed
Added 4 new functions in the sipx-utils.sh.in file
- checkRunningInstance
    - returns 0 if processes related with a regex and belonging to a user
    are found in the process table
    - return1 1 otherwise

- checkRunningInstanceTimeout
    - similar to checkRunningInstance
    - searches if process exists for a maximum amount of time by checking
    the process table periodically

-checkIfListening
  - using netstat check if the process related with the regex is listening
  on any port
- killAnyOrphans
   - in a loop search for processes that are related with a specified regex
   and belong to a specified user and kill them

modifications made to functions:
- start ()
    - no fork :
        - kill all related processes (killAnyOrphans)
        - launch process
    - daemon :
        - check to see if there is another instance of the process running
        (checkRunningInstance);if there is one exit with failure else launch
        process
        - check if process was launched (checkRunningInstanceTimeout)
        - check if listening on a port  (checkIfListening)
- stop ()
    - kill all related processes instead of killing by the pids found in the
    pidfile
- status
    - search for all related processes
    - for the java related scripts to see if the process is running the
    process table is checked
- condrestart
    - check in the process table if there is another instance of the same
    process running before restarting

diff --git a/sipXcdr/bin/sipxcdr.in b/sipXcdr/bin/sipxcdr.in
--- a/sipXcdr/bin/sipxcdr.in
+++ b/sipXcdr/bin/sipxcdr.in
@@ -76,6 +76,8 @@ fi
 resolverArgs="--daemon --confdir ${ConfDir} --logdir ${LogDir}"
 Database=SIPXCDR
 Today=`date`
+regex="${CallResolverMain}"
+prog="sipxcdr"
 
 PsqlCmd="${Psql} --tuples-only --no-align --username ${PgUser} --dbname ${Database}"
 
@@ -419,37 +421,52 @@ onSetup() {
 
 # Start CDR call resolver
 start() {
-	onSetup
-    # Check database version - don't run if it's wrong
-    echo $$ > ${PidFile}
-    databasePatch
-    if ! databaseVersionCheck; then
-       exit 1
-    fi
-    if [ -n "${NoFork}" ] ; then
-		runuser -s /bin/bash @SIPXPBXUSER@ -c "${RubyCmd} ${CallResolverMain} ${resolverArgs}"
-    else
-      echo -n $"Starting sipxcdr: "
-      runuser -s /bin/bash @SIPXPBXUSER@ -c "${RubyCmd} ${CallResolverMain} ${resolverArgs}" >/dev/null 2>&1 &
-      echo $! > ${PidFile}
-      echo_success
-    fi
+  onSetup
+  # Check database version - don't run if it's wrong
+  echo $$ > ${PidFile}
+  databasePatch
+  if ! databaseVersionCheck; then
+    exit 1
+  fi
+  if [ -n "${NoFork}" ] ; then
+    killAnyOrphans @SIPXPBXUSER@ $regex
+    runuser -s /bin/bash @SIPXPBXUSER@ -c "${RubyCmd} ${CallResolverMain} ${resolverArgs}"
+  else
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+ 
+    echo -n $"Starting ${prog}: "
+    runuser -s /bin/bash @SIPXPBXUSER@ -c "${RubyCmd} ${CallResolverMain} ${resolverArgs}" >/dev/null 2>&1 &
+    echo $! > ${PidFile}
+
+    #check if process was spawned
+    checkRunningInstanceTimeout @SIPXPBXUSER@ $regex
+    Status=$?
+    [ $Status -eq 0 ] && { echo_success; echo; exit $ESRCH; }
+    pid=`ps -u @SIPXPBXUSER@ -o pid,args | grep $regex | grep -v "grep" | awk '{print $1 }'`
+    checkIfListening $pid
+    Status=$? 
+    [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+    [ $Status -eq 0 ] && { echo_success; echo; }
+  fi
 }
 
 stop() {
-  echo -n $"Stopping sipxcdr: "
-  killproc -p "${PidFile}" "sipxcdr"
+  echo -n $"Stopping $prog: "
+  killAnyOrphans @SIPXPBXUSER@ $regex
+  checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
   Status=$?
-  echo
-  [ $Status -eq 0 ] && rm -f "${PidFile}"
+  [ $Status -eq 0 ] && { echo_failure; echo; exit $ERUNNING; }
+  [ $Status -eq 0 ] || { echo_success; echo; }
 }
 
 restart() {
-    stop
-    # sleep for no good reason. Can be disconcerting if stop/start
-    # switch is too fast IMHO
-    sleep 1
-    start
+  stop
+  # sleep for no good reason. Can be disconcerting if stop/start
+  # switch is too fast IMHO
+  sleep 1
+  start
 }
 
 case "$1" in
@@ -467,10 +484,13 @@ case "$1" in
     restart
     ;;
   condrestart)
-    [ -f ${pidfile} ] && restart || :
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p ${PidFile} sipxcdr
+    checkRunningInstance @SIPXPBXUSER@ $regex $prog
+    Status=$?
     ;;
   configtest)
     configCheck
@@ -493,4 +513,3 @@ case "$1" in
 esac
 
 exit $Status
-
diff --git a/sipXconfig/bin/sipxconfig.in b/sipXconfig/bin/sipxconfig.in
--- a/sipXconfig/bin/sipxconfig.in
+++ b/sipXconfig/bin/sipxconfig.in
@@ -65,6 +65,9 @@ PluginDir=@SIPX_JAVADIR@/sipXconfig/plugins
 CommonsLibDir=@SIPX_JAVADIR@/sipXcommons
 LogDir=@SIPX_LOGDIR@
 TmpDir=@SIPX_TMPDIR@
+prog=sipxconfig
+regex="Dprocname=sipxconfig"
+waitForListenPortTime=20
 
 . /etc/rc.d/init.d/functions || exit 1
 . @SIPX_LIBEXECDIR@/sipx-utils.sh
@@ -81,42 +84,37 @@ clearIndexLocks() {
   rm ${IndexDir}/*.lock 2>/dev/null
 }
 
-killAnyOrphans() {
-  procs=`ps -u @SIPXPBXUSER@ -o pid,args | grep '\-Dprocname=sipxconfig' | awk '{print $1 }'`
-  for pid in $procs; do kill -KILL $pid; done
-}
-
 # Turn control over to ant to run database command
 databaseCommand() {
-    clearIndexLocks
+  clearIndexLocks
 
-    # XCF-1275 - Do not want to suppress output if there is an error
-    # however want to be quiet if everything is ok for clean rpm install
-    # output
-    # ant.library.dir needs to be set - but should not point to any jars
-    Command="$JavaCmd \
-        -Dant.library.dir=${TmpDir} \
-        -Djava.net.preferIPv4Stack=true \
-        org.apache.tools.ant.launch.Launcher \
-        -emacs \
-        -quiet \
-        -Dlib.dir=${LibDir} \
-        -Dlog.dir=${LogDir} \
-        -Dtmp.dir=${TmpDir} \
-        -Dsipxconfig.db.user=@POSTGRESQL_USER@ \
-        ${SIPXCONFIG_ANT_OPTS} \
-        -f @SIPX_CONFDIR@/database/database.xml \
-        $@"
+  # XCF-1275 - Do not want to suppress output if there is an error
+  # however want to be quiet if everything is ok for clean rpm install
+  # output
+  # ant.library.dir needs to be set - but should not point to any jars
+  Command="$JavaCmd \
+      -Dant.library.dir=${TmpDir} \
+      -Djava.net.preferIPv4Stack=true \
+      org.apache.tools.ant.launch.Launcher \
+      -emacs \
+      -quiet \
+      -Dlib.dir=${LibDir} \
+      -Dlog.dir=${LogDir} \
+      -Dtmp.dir=${TmpDir} \
+      -Dsipxconfig.db.user=@POSTGRESQL_USER@ \
+      ${SIPXCONFIG_ANT_OPTS} \
+      -f @SIPX_CONFDIR@/database/database.xml \
+      $@"
 
-    CmdOut=`runuser -s @BASH@ @SIPXPBXUSER@ -c "${Command}"`
+  CmdOut=`runuser -s @BASH@ @SIPXPBXUSER@ -c "${Command}"`
 
-    if [ $? != "0" ]; then
-       echo "$CmdOut" | grep -v '^Unable to locate tools.jar' >&2
-    fi
+  if [ $? != "0" ]; then
+     echo "$CmdOut" | grep -v '^Unable to locate tools.jar' >&2
+  fi
 
-    if [ -d "@SIPX_VXMLDATADIR@/mailstore" ]; then
-      chown -R @SIPXPBXUSER@:@SIPXPBXGROUP@ @SIPX_VXMLDATADIR@/mailstore
-    fi
+  if [ -d "@SIPX_VXMLDATADIR@/mailstore" ]; then
+    chown -R @SIPXPBXUSER@:@SIPXPBXGROUP@ @SIPX_VXMLDATADIR@/mailstore
+  fi
 }
 
 setupCheck() {
@@ -129,57 +127,68 @@ setupCheck() {
 }
 
 buildCommand() {
-    procNameId=$1
+  procNameId=$1
 
-    setJavaSslOpts
+  setJavaSslOpts
 
-    # -Dprocname needs to be early in the command so cfengine can detect it
-    Command="$JavaCmd \
-       -Dprocname=${procNameId} \
-       -XX:MaxPermSize=128M \
-       -Xmx1024m \
-       ${SIPXCONFIG_OPTS} \
-       ${TrustStoreOpts} \
-       -Djava.io.tmpdir=${TmpDir} \
-       -Djetty.lib.dir=@SIPX_JAVADIR@/sipXconfig \
-       -Djetty.conf.dir=@SIPX_CONFDIR@ \
-       -Djetty.log.dir=${LogDir} \
-       -Dorg.apache.lucene.lockdir=${IndexDir} \
-       -Dorg.apache.commons.loging.Log=org.apache.commons.logging.impl.Log4JLogger \
-       -Djava.awt.headless=true"
+  # -Dprocname needs to be early in the command so cfengine can detect it
+  Command="$JavaCmd \
+     -Dprocname=${procNameId} \
+     -XX:MaxPermSize=128M \
+     -Xmx1024m \
+     ${SIPXCONFIG_OPTS} \
+     ${TrustStoreOpts} \
+     -Djava.io.tmpdir=${TmpDir} \
+     -Djetty.lib.dir=@SIPX_JAVADIR@/sipXconfig \
+     -Djetty.conf.dir=@SIPX_CONFDIR@ \
+     -Djetty.log.dir=${LogDir} \
+     -Dorg.apache.lucene.lockdir=${IndexDir} \
+     -Dorg.apache.commons.loging.Log=org.apache.commons.logging.impl.Log4JLogger \
+     -Djava.awt.headless=true"
 }
 
 runTask() {
-    setupCheck
-    databaseCommand upgrade
-    databaseVersionCheck    
-    buildCommand task-$taskId
-    Command="$Command org.sipfoundry.sipxconfig.common.SystemTaskRunner $*"
-    runuser -m -s @BASH@ @SIPXPBXUSER@ -c "${Command}"
-    Status=$?
+  setupCheck
+  databaseCommand upgrade
+  databaseVersionCheck    
+  buildCommand task-$taskId
+  Command="$Command org.sipfoundry.sipxconfig.common.SystemTaskRunner $*"
+  runuser -m -s @BASH@ @SIPXPBXUSER@ -c "${Command}"
+  Status=$?
 }
 
 
 # Run Web interface
 start() {
-    setupCheck
-    databaseCommand upgrade
-    databaseVersionCheck    
-    clearIndexLocks
-    killAnyOrphans
-    buildCommand sipxconfig
-    Command="$Command org.mortbay.jetty.Server @SIPX_CONFDIR@/sipxconfig-jetty.xml"
-    if [ -n "${NoFork}" ] ; then
-      runuser -m -s @BASH@ @SIPXPBXUSER@ -c "${Command}"
-      Status=$?
-    else
-      echo -n $"Starting sipxconfig: "
-      runuser -s @BASH@ @SIPXPBXUSER@ -c "${Command}" >/dev/null 2>&1 &
-      Status=$?
-      echo $! > ${PidFile}
-      echo
-      echo_success
-    fi
+  setupCheck
+  databaseCommand upgrade
+  databaseVersionCheck    
+  clearIndexLocks
+  buildCommand $prog
+  Command="$Command org.mortbay.jetty.Server @SIPX_CONFDIR@/sipxconfig-jetty.xml"
+  if [ -n "${NoFork}" ] ; then
+    killAnyOrphans @SIPXPBXUSER@ $regex
+    runuser -m -s @BASH@ @SIPXPBXUSER@ -c "${Command}"
+    Status=$?
+  else
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+
+    echo -n $"Starting $prog: "
+    runuser -s @BASH@ @SIPXPBXUSER@ -c "${Command}" >/dev/null 2>&1 &
+    echo $! > ${PidFile}
+
+    #check if process was spawned
+    checkRunningInstanceTimeout @SIPXPBXUSER@ $regex
+    Status=$?
+    pid=`ps -u @SIPXPBXUSER@ -o pid,args | grep $regex | grep -v "grep" | awk '{print $1 }'`
+    [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+    checkIfListening $pid $waitForListenPortTime
+    Status=$? 
+    [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+    [ $Status -eq 0 ] && { echo_success; echo; }
+  fi
 }
 
 # Return false if postgres is
@@ -230,32 +239,26 @@ EOF
 
 # simple diagnostics
 configtest() {
-    if ! databaseCheck
-    then
-      cat <<EOF
-    Postgres configuration database not detected.
-    Run (as root:)
+  if ! databaseCheck
+  then
+    cat <<EOF
+  Postgres configuration database not detected.
+  Run (as root:)
 
-       @bindir@/sipxconfig.sh --setup
+    @bindir@/sipxconfig.sh --setup
 EOF
-      Status=1
-    fi
-    Status=$(($Status+$?))
+    Status=1
+  fi
+  Status=$(($Status+$?))
 }
 
 stop() {
-  echo -n $"Stopping sipxconfig: "
-  killproc -p "${PidFile}" -d 10 sipxconfig
+  echo -n $"Stopping $prog: "
+  killAnyOrphans @SIPXPBXUSER@ $regex
+  checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
   Status=$?
-  if [ $Status -eq 0 ]; then
-     echo_success
-    [ $Status -eq 0 ] && rm -f "${PidFile}"
-  else
-    echo_failure
-  fi
-  echo
-  # found useful when orphans exist, we should add this to all service scripts
-  killAnyOrphans
+  [ $Status -eq 0 ] && { echo_failure; echo; exit $ERUNNING; }
+  [ $Status -eq 0 ] || { echo_success; echo; }
 }
 
 restart() {
@@ -286,10 +289,13 @@ case "$1" in
     restart
     ;;
   condrestart)
-    [ -f ${PidFile} ] && restart || :
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p ${PidFile} sipxconfig
+    checkRunningInstance @SIPXPBXUSER@ $regex $prog
+    Status=$?
     ;;
   configtest)
     configtest
diff --git a/sipXfreeSwitch/bin/sipxfreeswitch.in b/sipXfreeSwitch/bin/sipxfreeswitch.in
--- a/sipXfreeSwitch/bin/sipxfreeswitch.in
+++ b/sipXfreeSwitch/bin/sipxfreeswitch.in
@@ -11,6 +11,7 @@
 # Source function library.
 . /etc/init.d/functions
 . /etc/sysconfig/network
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || exit 1
 
 PATH=/sbin:/usr/sbin:/bin:/usr/bin:@FREESWITCH_PREFIX@/bin
 DESC="FreeSwitch Voice Switching System"
@@ -79,73 +80,79 @@ do_audio_setup() {
 base=${0##*/}
 
 do_start() {
-        do_setlimits
-        do_permission_check
-	do_audio_setup
-        $DAEMON $DAEMON_START_ARGS
-        RETVAL=$?
-        if [ $RETVAL = 0 ]; then
-                success $"$base startup"
-        else
-                failure $"$base startup"
-        fi
-        echo
-        return $RETVAL
+  checkRunningInstance @SIPXPBXUSER@ $NAME > /dev/null
+  RETVAL=$?
+  [ $RETVAL -eq 0 ] && { echo -n "$NAME $runningError"; echo_failure; echo; exit $ERUNNING; } 
+  do_setlimits
+  do_permission_check
+  do_audio_setup
+  $DAEMON $DAEMON_START_ARGS
+  
+  #check if process spawned
+  checkRunningInstanceTimeout @SIPXPBXUSER@ $NAME
+  RETVAL=$?
+  [ $RETVAL -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+  checkIfListening $NAME 
+  RETVAL=$? 
+  [ $RETVAL -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+  [ $RETVAL -eq 0 ] && { echo_success; echo; }
+  return $RETVAL
 }
 
 do_stop() {
-	fspid=$(pidof $NAME)
+  fspid=$(pidof $NAME)
+  status=$?
+  $DAEMON $DAEMON_STOP_ARGS
+  RETVAL=$?
+  [ $RETVAL = 0 ] && success $"$base shutdown" || failure $"$base shutdown"
+  echo "Waiting for daemon to exit..."
+  i=0
+  while [[ $status -lt 1 && $i -lt 10 ]]
+    do
+    sleep 1
+      fspid=$(pidof $NAME)
 	status=$?
-	$DAEMON $DAEMON_STOP_ARGS
-        RETVAL=$?
-        [ $RETVAL = 0 ] && success $"$base shutdown" || failure $"$base shutdown"
-	echo "Waiting for daemon to exit..."
-	i=0
-	while [[ $status -lt 1 && $i -lt 10 ]]
-	do
-		sleep 1
-		fspid=$(pidof $NAME)
-		status=$?
-		i=$(expr $i + 1)
-	done
-	if [ $status -lt 1 ]; then
-		echo "Process did not exit cleanly. Aborting..."
-		killproc $NAME	
-        fi
-	rm -f $LOCKFILE
-        echo
-        return $RETVAL
+	i=$(expr $i + 1)
+  done
+  if [ $status -lt 1 ]; then
+    echo "Process did not exit cleanly. Aborting..."
+    killproc $NAME	
+  fi
+  rm -f $LOCKFILE
+  echo
+  killAnyOrphans @SIPXPBXUSER@ $NAME
+  return $RETVAL
 }
 
 do_reload() {
-        $FS_CLI -x "reloadXml"
-        RETVAL=$?
-        echo
-        return $RETVAL
+  $FS_CLI -x "reloadXml"
+  RETVAL=$?
+  echo
+  return $RETVAL
 }
 
 # See how we were called.
 case "$1" in
   start)
-        do_start
-        ;;
+    do_start
+  ;;
   stop)
-        do_stop
-        ;;
+    do_stop
+  ;;
   reload)
-        do_reload
-        ;;
+    do_reload
+  ;;
   restart)
-        do_stop
-        do_start
-        ;;
+    do_stop
+    do_start
+  ;;
   status)
-        status -p ${PIDFILE} sipxfreeswitch
-    ;;
+    status $NAME
+  ;;
   *)
-        echo $"Usage: $0 {start|stop|status}"
-        exit 2
-        ;;
+    echo $"Usage: $0 {start|stop|status}"
+    exit 2
+  ;;
 esac
 
 exit $RETVAL
diff --git a/sipXprovision/bin/sipxprovision.in b/sipXprovision/bin/sipxprovision.in
--- a/sipXprovision/bin/sipxprovision.in
+++ b/sipXprovision/bin/sipxprovision.in
@@ -14,18 +14,9 @@
 prog=sipxprovision
 pidfile="@SIPX_RUNDIR@/sipxprovision.pid"
 config="@SIPX_CONFDIR@/sipxprovision-config"
+regex="Dprocname=sipxprovision"
 
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
-
-checkRunningInstance() {
-  if [ -f "${pidfile}" ]; then
-    pid=`cat ${pidfile}`
-    if checkpid $pid 2>&1; then
-      echo "Process $prog is already running with pid $pid"
-      exit 1
-    fi
-  fi
-}
 
 configtest() {	
   # Check that the config gile exists.	  
@@ -43,9 +34,7 @@ configtest() {
 
 # Start sipxrecording
 start() {
-  checkRunningInstance
-  
-  [ -f $config ] || exit 6
+  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; echo; exit 6; }
   
   JavaCmd=`@SIPX_BINDIR@/sipx-config --java`
   Dependencies=`@SIPX_BINDIR@/java-dep -d @SIPX_JAVADIR@/sipXcommons @provision_PKGS@`
@@ -56,31 +45,46 @@ start() {
   Command="$JavaCmd \
     -Dprocname=sipxprovision \
     $TrustStoreOpts \
-	$KeyStoreOpts \
+    $KeyStoreOpts \
     ${SIPXPROVISION_OPTS} \
     -Djetty.x509.algorithm=$X509Algorithm \
-	-Djetty.ssl.password=$StorePassword \
-	-Djetty.ssl.keypassword=$StorePassword	\
+    -Djetty.ssl.password=$StorePassword \
+    -Djetty.ssl.keypassword=$StorePassword	\
     -Dconf.dir=@SIPX_CONFDIR@ \
     -Dvar.dir=@SIPX_VARDIR@ \
     org.sipfoundry.sipxprovision.SipXprovision \
     $Args"
   if [ -n "${NoFork}" ] ; then
+    killAnyOrphans @SIPXPBXUSER@ $regex
     runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}"
   else
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+
     echo -n $"Starting $prog: "
     runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}" >/dev/null 2>&1 &
     echo $! > ${pidfile}
-    echo_success
+    
+    #check if process was spawned
+    checkRunningInstanceTimeout @SIPXPBXUSER@ $regex
+    Status=$?
+    [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+    pid=`ps -u @SIPXPBXUSER@ -o pid,args | grep $regex | grep -v "grep" | awk '{print $1 }'`
+    checkIfListening $pid
+    Status=$? 
+    [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+    [ $Status -eq 0 ] && { echo_success; echo; }
   fi  
 }
 
 stop() {
-  echo -n $"Stopping sipxprovision: "
-  killproc -p "${pidfile}" "sipxprovision"
+  echo -n $"Stopping $prog: "
+  killAnyOrphans @SIPXPBXUSER@ $regex
+  checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
   Status=$?
-  echo
-  [ $Status -eq 0 ] && rm -f "${pidfile}"
+  [ $Status -eq 0 ] && { echo_failure; echo; exit $ERUNNING; }
+  [ $Status -eq 0 ] || { echo_success; echo; }
 }
 
 restart() {
@@ -106,10 +110,13 @@ case "$1" in
     restart
     ;;
   condrestart)
-    [ -f ${pidfile} ] && restart || :
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p ${pidfile} sipxprovision
+    checkRunningInstance @SIPXPBXUSER@ $regex $prog
+    Status=$?
     ;;
   configtest)
     configtest
diff --git a/sipXpublisher/bin/sipxpublisher.in b/sipXpublisher/bin/sipxpublisher.in
--- a/sipXpublisher/bin/sipxpublisher.in
+++ b/sipXpublisher/bin/sipxpublisher.in
@@ -22,6 +22,7 @@
 . @SIPX_LIBEXECDIR@/sipx-utils.sh || exit 1
 
 prog=sipstatus
+progName=sipxpublisher
 exec="@SIPX_BINDIR@/${prog}"
 config="@SIPX_CONFDIR@/status-config"
 pidfile="@SIPX_RUNDIR@/sipxpublisher.pid"
@@ -29,25 +30,37 @@ pidfile="@SIPX_RUNDIR@/sipxpublisher.pid"
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
 
 start() {
-    [ -x $exec ] || exit 5
-    [ -f $config ] || exit 6
-    if [ -n "${NoFork}" ] ; then
-      runuser - @SIPXPBXUSER@ -c $exec
-      Status=$?
-    else
-      echo -n $"Starting sipxpublisher: "
-      daemon --user @SIPXPBXUSER@ --pidfile $pidfile $exec $pidfile
-      Status=$?
-      echo_success
-    fi
+  [ -x $exec ] || { echo -n "$execError"; echo_failure; echo; exit $ENOEXEC; }
+  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; echo; exit $ENOENT; }
+  if [ -n "${NoFork}" ] ; then
+    killAnyOrphans @SIPXPBXUSER@ $prog
+    runuser - @SIPXPBXUSER@ -c $exec
+  else
+    checkRunningInstance @SIPXPBXUSER@ $prog > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && { echo -n "$progName $runningError"; echo_failure; echo; exit $ERUNNING; }
+    
+    echo -n $"Starting $progName: "
+    daemon --user @SIPXPBXUSER@ --pidfile $pidfile $exec $pidfile
+    
+    #check if process spawned
+    checkRunningInstanceTimeout @SIPXPBXUSER@ $prog
+    Status=$?
+    [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+    checkIfListening $prog
+    Status=$? 
+    [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+    [ $Status -eq 0 ] && { echo_success; echo; }
+  fi
 }
 
 stop() {
-  echo -n $"Stopping sipxpublisher: "
-  killproc -p "${pidfile}" "${exec}"
+  echo -n $"Stopping $progName: "
+  killproc "${exec}"
   Status=$?
   echo
   [ $Status -eq 0 ] && rm -f "${pidfile}"
+  killAnyOrphans @SIPXPBXUSER@ $prog
 }
 
 restart() {
@@ -85,10 +98,12 @@ case "$1" in
     restart
     ;;
   condrestart)
-    [ -f ${pidfile} ] && restart || :
+    checkRunningInstance @SIPXPBXUSER@ $prog > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p ${pidfile} sipxpublisher
+    status "${prog}"
     Status=$?
     ;;
   configtest)
diff --git a/sipXtunnel/tunnel.in b/sipXtunnel/tunnel.in
--- a/sipXtunnel/tunnel.in
+++ b/sipXtunnel/tunnel.in
@@ -31,14 +31,34 @@ USAGE
 
 Status=0
 PidFile=@SIPX_RUNDIR@/tunnel-@MODE@.pid
+[ @MODE@ = "server" ] && regex=".*/stunnel\\s.*/tunnel-server.ini"
+[ @MODE@ = "client" ] && regex=".*/stunnel\\s.*/tunnel-client.ini"
 
 start() {
-    echo "Starting tunnel service in @MODE@ mode..."
-    /usr/bin/stunnel @SIPX_CONFDIR@/tunnel-@MODE@.ini
+  checkRunningInstance  "root" $regex > /dev/null
+  [ $? -eq 0 ] && { echo -n "@MODE@ $runningError"; echo_failure; echo; exit $ERUNNING; }
+  echo -n "Starting tunnel service in @MODE@ mode..."
+  /usr/bin/stunnel @SIPX_CONFDIR@/tunnel-@MODE@.ini
+
+  #check if process was spawned
+  checkRunningInstanceTimeout "root" $regex
+  Status=$?
+  [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+  pid=`ps -u "root" -o pid,args | grep $regex | grep -v "grep" | tail -1 | awk '{print $1 }'`
+  checkIfListening $pid
+  Status=$? 
+  [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+  [ $Status -eq 0 ] && { echo_success; echo; }
 }
 
 stop() {
-    sipx_stop tunnel ${PidFile}
+  sipx_stop tunnel ${PidFile}
+  killAnyOrphans root $regex
+}
+
+restart() {
+  stop
+  start
 }
 
 case "$1" in
@@ -53,14 +73,16 @@ case "$1" in
     stop
     ;;
   restart|reload|force-reload)
-    stop
-    start
+    restart
     ;;
   condrestart)
-    [ -f ${PidFile} ] && restart || :
+    checkRunningInstance  root $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p ${PidFile} tunnel-@MODE@
+    checkRunningInstance root $regex tunnel-@MODE@
+    Status=$?
     ;;
   configtest)
     configtest
