UC-647 Improve init scripts http://track.sipfoundry.org/browse/UC-647
-processes are now killed by name

-If extra argument is provided to start function then we check to
see if process launched successfully.
There are 2 checks:
  -look in the process table to see if process was spawned
  -check if process is listening on a port.
  Both of these checks have a timeout.

- "restart" uses "start" that checks to see if process was successfully
launched

-Added "asyncrestart" function which calls "start" that doesn't do
any verification.

- Cfengine scripts now use asyncrestart instead of restart because
the additional checks would increase launching time of process

Added 4 new functions in the sipx-utils.sh file

  -checkRunningInstance
    - search in process table for process belonging to a specified user
    and related to a specified regex
    - checks to see if process is running and is listening on a port
    using netstat

  -checkRunningInstanceTimeout
    - checks to see if process shows up in process table for a given
    amount of time

  -checkIfListening
    - checks if process is listening on a port

  -killAnyOrphans
    - kills all related processes
    - first try with SIGTERM and if it fails try with SIGKILL

Modifications made to init script functions
- start()
    -no fork
      - kill all related processes
      - launch process
    - daemon:
      - exit with failure if another instance is running
      - launch process
      - if extra argument is provided to "start" function
      then :
        - check if process was launched
        - check if listening on port

- stop()
  - doesn't kill using pid found in pidfile
  - kills all related processes

- status()
  - uses checkRunningInstance

Defined timeouts
- maxTimeout - maximum timeout for process to show up in process table
is set to 25 ( sleep 0.5 is executed 25 times)
- maxListenTimeout - maximum timeout for process to listen on a port
is set to 60
- waitForListenPortTime - wait time for sipXconfig to listen on a port
is set to 60

diff --git a/sipXcdr/bin/sipxcdr.in b/sipXcdr/bin/sipxcdr.in
--- a/sipXcdr/bin/sipxcdr.in
+++ b/sipXcdr/bin/sipxcdr.in
@@ -11,8 +11,8 @@
 # Contributors retain copyright to elements licensed under a Contributor Agreement.
 # Licensed to the User under the LGPL license.
 
-. /etc/rc.d/init.d/functions || exit 1
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || exit 1
+. /etc/rc.d/init.d/functions || exit $ENOENT
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
 
 usage() {
 cat <<USAGE
@@ -76,6 +76,8 @@ fi
 resolverArgs="--daemon --confdir ${ConfDir} --logdir ${LogDir}"
 Database=SIPXCDR
 Today=`date`
+regex="${CallResolverMain}"
+prog="sipxcdr"
 
 PsqlCmd="${Psql} --tuples-only --no-align --username ${PgUser} --dbname ${Database}"
 
@@ -84,7 +86,7 @@ assertRoot() {
     user=`whoami`
     if [ "${user}" != "root" ]; then
       echo "Error: Must be root to run sipxcdr script." >&2
-      exit 1
+      exit $EINCORRECTUSAGE
     fi
 }
 
@@ -419,37 +421,64 @@ onSetup() {
 
 # Start CDR call resolver
 start() {
-	onSetup
-    # Check database version - don't run if it's wrong
-    echo $$ > ${PidFile}
-    databasePatch
-    if ! databaseVersionCheck; then
-       exit 1
-    fi
-    if [ -n "${NoFork}" ] ; then
-		runuser -s /bin/bash @SIPXPBXUSER@ -c "${RubyCmd} ${CallResolverMain} ${resolverArgs}"
+  onSetup
+  # Check database version - don't run if it's wrong
+  echo $$ > ${PidFile}
+  databasePatch
+  if ! databaseVersionCheck; then
+    exit 1
+  fi
+  if [ -n "${NoFork}" ] ; then
+    killAnyOrphans @SIPXPBXUSER@ $regex
+    runuser -s /bin/bash @SIPXPBXUSER@ -c "${RubyCmd} ${CallResolverMain} ${resolverArgs}"
+  else
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+
+    echo -n $"Starting ${prog}: "
+    runuser -s /bin/bash @SIPXPBXUSER@ -c "${RubyCmd} ${CallResolverMain} ${resolverArgs}" >/dev/null 2>&1 &
+    echo $! > ${PidFile}
+
+    if [ $# -gt 0 ]; then
+      #check if process was spawned
+      checkRunningInstanceTimeout @SIPXPBXUSER@ $regex
+      Status=$?
+      [ $Status -eq 0 ] && { echo_success; echo; exit $ESRCH; }
+      pid=`ps -u @SIPXPBXUSER@ -o pid,args | grep $regex | grep -v "grep" | awk '{print $1 }'`
+      checkIfListening $pid
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; echo; }
     else
-      echo -n $"Starting sipxcdr: "
-      runuser -s /bin/bash @SIPXPBXUSER@ -c "${RubyCmd} ${CallResolverMain} ${resolverArgs}" >/dev/null 2>&1 &
-      echo $! > ${PidFile}
-      echo_success
+      echo_success; echo;
     fi
+  fi
 }
 
 stop() {
-  echo -n $"Stopping sipxcdr: "
-  killproc -p "${PidFile}" "sipxcdr"
+  echo -n $"Stopping $prog: "
+  killAnyOrphans @SIPXPBXUSER@ $regex
+  checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
   Status=$?
-  echo
-  [ $Status -eq 0 ] && rm -f "${PidFile}"
+  [ $Status -eq 0 ] && { echo_failure; echo; exit $ERUNNING; }
+  [ $Status -eq 0 ] || { echo_success; echo; }
 }
 
 restart() {
-    stop
-    # sleep for no good reason. Can be disconcerting if stop/start
-    # switch is too fast IMHO
-    sleep 1
-    start
+  stop
+  # sleep for no good reason. Can be disconcerting if stop/start
+  # switch is too fast IMHO
+  sleep 1
+  start $withCheck
+}
+
+asyncrestart() {
+  stop
+  # sleep for no good reason. Can be disconcerting if stop/start
+  # switch is too fast IMHO
+  sleep 1
+  start
 }
 
 case "$1" in
@@ -458,7 +487,7 @@ case "$1" in
     start
     ;;
   start)
-	start
+	start $withCheck
 	;;
   stop)
     stop
@@ -466,11 +495,17 @@ case "$1" in
   restart|reload|force-reload)
     restart
     ;;
+  asyncrestart)
+    asyncrestart
+    ;;
   condrestart)
-    [ -f ${pidfile} ] && restart || :
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p ${PidFile} sipxcdr
+    checkRunningInstance @SIPXPBXUSER@ $regex $prog
+    Status=$?
     ;;
   configtest)
     configCheck
@@ -488,9 +523,8 @@ case "$1" in
     configCheck
     ;;
   *)
-    echo "Usage: $0 {start|stop|distrib-configtest|patch|database|setup|configtest|db}"
-    Status=1
+    echo "Usage: $0 {start|stop|restart|asyncrestart|distrib-configtest|patch|database|setup|configtest|db}"
+    Status=$EINCORRECTUSAGE
 esac
 
 exit $Status
-
diff --git a/sipXfreeSwitch/bin/sipxfreeswitch.in b/sipXfreeSwitch/bin/sipxfreeswitch.in
--- a/sipXfreeSwitch/bin/sipxfreeswitch.in
+++ b/sipXfreeSwitch/bin/sipxfreeswitch.in
@@ -11,6 +11,7 @@
 # Source function library.
 . /etc/init.d/functions
 . /etc/sysconfig/network
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
 
 PATH=/sbin:/usr/sbin:/bin:/usr/bin:@FREESWITCH_PREFIX@/bin
 DESC="FreeSwitch Voice Switching System"
@@ -79,73 +80,97 @@ do_audio_setup() {
 base=${0##*/}
 
 do_start() {
-        do_setlimits
-        do_permission_check
-	do_audio_setup
-        $DAEMON $DAEMON_START_ARGS
-        RETVAL=$?
-        if [ $RETVAL = 0 ]; then
-                success $"$base startup"
-        else
-                failure $"$base startup"
-        fi
-        echo
-        return $RETVAL
+  checkRunningInstance @SIPXPBXUSER@ $NAME > /dev/null
+  RETVAL=$?
+  [ $RETVAL -eq 0 ] && { echo -n "$NAME $runningError"; echo_failure; echo; exit $ERUNNING; }
+  do_setlimits
+  do_permission_check
+  do_audio_setup
+  $DAEMON $DAEMON_START_ARGS
+  RETVAL=$?
+
+  if [ $# -gt 0 ]; then
+    #check if process spawned
+    checkRunningInstanceTimeout @SIPXPBXUSER@ $NAME
+    RETVAL=$?
+    [ $RETVAL -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+    checkIfListening $NAME
+    RETVAL=$?
+    [ $RETVAL -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+    [ $RETVAL -eq 0 ] && { echo_success; echo; }
+  else
+    [ $RETVAL -eq 0 ] && { echo_success; echo; }
+    [ $RETVAL -eq 0 ] || { echo_failure; echo; }
+    return $RETVAL
+  fi
 }
 
 do_stop() {
-	fspid=$(pidof $NAME)
-	status=$?
-	$DAEMON $DAEMON_STOP_ARGS
-        RETVAL=$?
-        [ $RETVAL = 0 ] && success $"$base shutdown" || failure $"$base shutdown"
-	echo "Waiting for daemon to exit..."
-	i=0
-	while [[ $status -lt 1 && $i -lt 10 ]]
-	do
-		sleep 1
-		fspid=$(pidof $NAME)
-		status=$?
-		i=$(expr $i + 1)
-	done
-	if [ $status -lt 1 ]; then
-		echo "Process did not exit cleanly. Aborting..."
-		killproc $NAME	
-        fi
-	rm -f $LOCKFILE
-        echo
-        return $RETVAL
+  fspid=$(pidof $NAME)
+  status=$?
+  $DAEMON $DAEMON_STOP_ARGS
+  RETVAL=$?
+  [ $RETVAL = 0 ] && success $"$base shutdown" || failure $"$base shutdown"
+  echo "Waiting for daemon to exit..."
+  i=0
+  while [[ $status -lt 1 && $i -lt 10 ]]
+    do
+    sleep 1
+      fspid=$(pidof $NAME)
+  status=$?
+  i=$(expr $i + 1)
+  done
+  if [ $status -lt 1 ]; then
+    echo "Process did not exit cleanly. Aborting..."
+    killproc $NAME
+  fi
+  rm -f $LOCKFILE
+  echo
+  killAnyOrphans @SIPXPBXUSER@ $NAME
+  return $RETVAL
 }
 
 do_reload() {
-        $FS_CLI -x "reloadXml"
-        RETVAL=$?
-        echo
-        return $RETVAL
+  $FS_CLI -x "reloadXml"
+  RETVAL=$?
+  echo
+  return $RETVAL
+}
+
+do_restart() {
+  do_stop
+  do_start $withCheck
+}
+
+do_asyncrestart() {
+  do_stop
+  do_start
 }
 
 # See how we were called.
 case "$1" in
   start)
-        do_start
-        ;;
+    do_start $withCheck
+    ;;
   stop)
-        do_stop
-        ;;
+    do_stop
+    ;;
   reload)
-        do_reload
-        ;;
+    do_reload
+    ;;
   restart)
-        do_stop
-        do_start
-        ;;
+    do_restart
+    ;;
+  asyncrestart)
+    do_asyncrestart
+    ;;
   status)
-        status -p ${PIDFILE} sipxfreeswitch
+    checkRunningInstance @SIPXPBXUSER@ $NAME
     ;;
   *)
-        echo $"Usage: $0 {start|stop|status}"
-        exit 2
-        ;;
+    echo $"Usage: $0 {start|stop|status}"
+    exit $EINCORRECTUSAGE
+    ;;
 esac
 
 exit $RETVAL
diff --git a/sipXivr/bin/sipxivr.in b/sipXivr/bin/sipxivr.in
--- a/sipXivr/bin/sipxivr.in
+++ b/sipXivr/bin/sipxivr.in
@@ -5,71 +5,84 @@
 # description: sipxivr is a IVR subystem that uses FreeSWITCH as a media server
 # processname: sipxivr
 
-# Copyright (C) 2007 Pingtel Corp., certain elements licensed under a Contributor Agreement.  
+# Copyright (C) 2007 Pingtel Corp., certain elements licensed under a Contributor Agreement.
 # Contributors retain copyright to elements licensed under a Contributor Agreement.
 # Licensed to the User under the LGPL license.
 
-. /etc/rc.d/init.d/functions || exit 1
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || exit 1
+. /etc/rc.d/init.d/functions || exit $ENOENT
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
 
 prog=sipxivr
 pidfile="@SIPX_RUNDIR@/sipxivr.pid"
+regex="Dprocname=sipxivr"
 
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
 
-checkRunningInstance() {
-  if [ -f "${pidfile}" ]; then
-    pid=`cat ${pidfile}`
-    if checkpid $pid 2>&1; then
-      echo "Process $prog is already running with pid $pid"
-      exit 1
+start() {
+  JavaCmd=`@SIPX_BINDIR@/sipx-config --java`
+  Dependencies=`@SIPX_BINDIR@/java-dep -d @SIPX_JAVADIR@/sipXcommons @ivr_PKGS@`
+  export CLASSPATH=`echo @SIPX_CONFDIR@/sipxivr @SIPX_JAVADIR@/{sipXivr,sipXopenfire/plugins}/*.jar ${Dependencies} | sed -e 's/ /:/g'`
+
+  setJavaSslOpts
+
+  # procname is there so cfengine can find it
+  Command="$JavaCmd \
+    -Dprocname=sipxivr \
+    -Dconf.dir=@SIPX_CONFDIR@ \
+    -Dvar.dir=@SIPX_VARDIR@ \
+    $JavaSslOpts \
+    ${SIPXIVR_OPTS} \
+    org.sipfoundry.sipxivr.SipXivrServer \
+    ${@}"
+  if [ -n "${NoFork}" ] ; then
+    killAnyOrphans @SIPXPBXUSER@ $regex
+    runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}"
+  else
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+
+    echo -n $"Starting $prog: "
+    runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}" >/dev/null 2>&1 &
+    echo $! > ${pidfile}
+
+    if [ $# -gt 1 ]; then
+      #check if process was spawned
+      checkRunningInstanceTimeout @SIPXPBXUSER@ $regex
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+      pid=`ps -u @SIPXPBXUSER@ -o pid,args | grep $regex | grep -v "grep" | awk '{print $1 }'`
+      checkIfListening $pid
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; echo; }
+    else
+      echo_success; echo;
     fi
   fi
 }
 
-start() {
-    checkRunningInstance
-
-    JavaCmd=`@SIPX_BINDIR@/sipx-config --java`
-    Dependencies=`@SIPX_BINDIR@/java-dep -d @SIPX_JAVADIR@/sipXcommons @ivr_PKGS@`
-    export CLASSPATH=`echo @SIPX_CONFDIR@/sipxivr @SIPX_JAVADIR@/{sipXivr,sipXopenfire/plugins}/*.jar ${Dependencies} | sed -e 's/ /:/g'`
-
-    setJavaSslOpts
-
-    # procname is there so cfengine can find it
-    Command="$JavaCmd \
-      -Dprocname=sipxivr \
-      -Dconf.dir=@SIPX_CONFDIR@ \
-      -Dvar.dir=@SIPX_VARDIR@ \
-      $JavaSslOpts \
-      ${SIPXIVR_OPTS} \
-      org.sipfoundry.sipxivr.SipXivrServer \
-      ${@}"
-    if [ -n "${NoFork}" ] ; then
-      runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}"
-    else
-      echo -n $"Starting $prog: "
-      runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}" >/dev/null 2>&1 &
-      echo $! > ${pidfile}
-      echo_success
-    fi
-}
-
 stop() {
-  echo -n $"Stopping sipxivr: "
-  killproc -p "${pidfile}" "sipxivr"
+  echo -n $"Stopping $prog: "
+  killAnyOrphans @SIPXPBXUSER@ $regex
+  checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
   Status=$?
-  echo
-  [ $Status -eq 0 ] && rm -f "${pidfile}"
+  [ $Status -eq 0 ] && { echo_failure; echo; exit $ERUNNING; }
+  [ $Status -eq 0 ] || { echo_success; echo; }
 }
 
 restart() {
+  stop
+  start $withCheck
+}
+
+asyncrestart() {
   stop
   start
 }
 
 configtest() {
-  sipx_config_exists @SIPX_CONFDIR@/sipxivr.properties 
+  sipx_config_exists @SIPX_CONFDIR@/sipxivr.properties
   Status=$(($Status+$?))
 
   # check validity of xml files
@@ -81,7 +94,7 @@ configtest() {
   if [ -e $logfile -a ! -w $logfile ]
   then
       echo "Log file '$logfile' exists but is not writable." >&2
-      Status=1
+      Status=$ENOTWRITABLE
   fi
 }
 
@@ -91,7 +104,7 @@ case "$1" in
     start
     ;;
   start)
-    start ${@}
+    start ${@} $withCheck
     ;;
   stop)
     stop
@@ -99,18 +112,24 @@ case "$1" in
   restart|reload|force-reload)
     restart
     ;;
+  asyncrestart)
+    asyncrestart
+    ;;
   condrestart)
-    [ -f ${pidfile} ] && restart || :
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p ${pidfile} sipxivr
+    checkRunningInstance @SIPXPBXUSER@ $regex $prog
+    Status=$?
     ;;
   configtest)
     configtest
     ;;
   *)
-    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|nofork}"
-    Status=1
+    echo "Usage: $0 {start|stop|status|restart|asyncrestart|reload|force-reload|condrestart|nofork}"
+    Status=$EINCORRECTUSAGE
 esac
 
 exit $Status
diff --git a/sipXmongo/bin/mongod-arbiter.in b/sipXmongo/bin/mongod-arbiter.in
--- a/sipXmongo/bin/mongod-arbiter.in
+++ b/sipXmongo/bin/mongod-arbiter.in
@@ -11,16 +11,18 @@
 # NOTE: This file cloned from /etc/init.d/mongod from mongodb proper
 
 . /etc/rc.d/init.d/functions
-
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
 # things from mongod.conf get there by mongod reading it
 
 
 # NOTE: if you change any OPTIONS here, you get what you pay for:
 # this script assumes all options are in the config file.
+PROG="mongod-arbiter"
 CONFIGFILE="/etc/mongod-arbiter.conf"
 OPTIONS=" -f $CONFIGFILE"
 SYSCONFIG="/etc/sysconfig/mongod-arbiter"
 LOCKFILE=/var/lock/subsys/mongod-arbiter
+regex="mongod"
 
 # 10gen v.s. fedora
 if `id mongodb 1>/dev/null 2>&1` ; then
@@ -33,7 +35,7 @@ else
   MONGO_GROUP=mongod
 fi
 
-test -f $CONFIGFILE || exit 5
+test -f $CONFIGFILE || { echo_failure; echo; exit $ENOENT; }
 
 # FIXME: 1.9.x has a --shutdown flag that parses the config file and
 # shuts down the correct running pid, but that's unavailable in 1.8
@@ -49,25 +51,48 @@ chown $MONGO_USER:$MONGO_GROUP $DBPATH
 
 start()
 {
-  echo -n $"Starting mongod-arbiter: "
-  daemon --user "$MONGO_USER" $mongod $OPTIONS
+  checkRunningInstance $MONGO_USER $PROG > /dev/null
+  Status=$?
+  [ $Status -eq 0 ] && { echo -n "$PROG $runningError"; echo_failure; echo; exit $ERUNNING; }
+  echo -n $"Starting $PROG: "
+  daemon --user "$MONGO_USER" $mongod $OPTIONS > /dev/null
   RETVAL=$?
-  echo
-  [ $RETVAL -eq 0 ] && touch $LOCKFILE
+
+  if [ $# -gt 0 ]; then
+    #check if process was spawned
+    checkRunningInstanceTimeout $MONGO_USER $PROG
+    RETVAL=$?
+    [ $RETVAL -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+    pid=`ps -u $MONGO_USER -o pid,args | grep $regex | grep -v "grep" | awk '{print $1 }'`
+    checkIfListening $pid
+    RETVAL=$?
+    [ $RETVAL -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+    [ $RETVAL -eq 0 ] && touch $LOCKFILE
+    [ $RETVAL -eq 0 ] && { echo_success; echo; }
+  else
+    [ $RETVAL -eq 0 ] && { echo_success; echo; }
+    [ $RETVAL -eq 0 ] || { echo_failure; echo; }
+  fi
 }
 
 stop()
 {
-  echo -n $"Stopping mongod-arbiter: "
-  killproc -p $PIDFILE $mongod
+  echo -n $"Stopping $PROG: "
+  killproc $mongod
   RETVAL=$?
   echo
   [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
+  killAnyOrphans $MONGO_USER $PROG
 }
 
-restart () {
-	stop
-	start
+restart() {
+  stop
+  start $withCheck
+}
+
+asyncrestart() {
+  stop
+  start
 }
 
 ulimit -n 12000
@@ -75,7 +100,7 @@ RETVAL=0
 
 case "$1" in
   start)
-    start
+    start $withCheck
     ;;
   stop)
     stop
@@ -83,16 +108,21 @@ case "$1" in
   restart|reload|force-reload)
     restart
     ;;
+  asyncrestart)
+    asyncrestart
+    ;;
   condrestart)
-    [ -f $LOCKFILE ] && restart || :
+    checkRunningInstance $MONGO_USER $PROG $PROG > /dev/null
+    RETVAL=$?
+    [ $RETVAL -eq 0 ] && [ -f $LOCKFILE ] && restart || :
     ;;
   status)
-    status -p $PIDFILE "mongod-arbiter"
+    checkRunningInstance $MONGO_USER $PROG
     RETVAL=$?
     ;;
   *)
-    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
-    RETVAL=1
+    echo "Usage: $0 {start|stop|status|restart|asyncrestart|reload|force-reload|condrestart}"
+    RETVAL=$EINCORRECTUSAGE
 esac
 
 exit $RETVAL
diff --git a/sipXprovision/bin/sipxprovision.in b/sipXprovision/bin/sipxprovision.in
--- a/sipXprovision/bin/sipxprovision.in
+++ b/sipXprovision/bin/sipxprovision.in
@@ -8,24 +8,15 @@
 # Contributors retain copyright to elements licensed under a Contributor Agreement.
 # Licensed to the User under the AGPL license.
 
-. /etc/rc.d/init.d/functions || exit 1
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || exit 1
+. /etc/rc.d/init.d/functions || exit $ENOENT
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
 
 prog=sipxprovision
 pidfile="@SIPX_RUNDIR@/sipxprovision.pid"
 config="@SIPX_CONFDIR@/sipxprovision-config"
+regex="Dprocname=sipxprovision"
 
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
-
-checkRunningInstance() {
-  if [ -f "${pidfile}" ]; then
-    pid=`cat ${pidfile}`
-    if checkpid $pid 2>&1; then
-      echo "Process $prog is already running with pid $pid"
-      exit 1
-    fi
-  fi
-}
 
 configtest() {	
   # Check that the config gile exists.	  
@@ -37,15 +28,13 @@ configtest() {
   if [ -e $logfile -a ! -w $logfile ]
   then
     echo "Log file '$logfile' exists but is not writable by user '@SIPXPBXUSER@'." >&2
-    Status=1
+    Status=$ENOTWRITABLE
   fi
 }
 
 # Start sipxrecording
 start() {
-  checkRunningInstance
-  
-  [ -f $config ] || exit 6
+  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; echo; exit $ENOENT; }
   
   JavaCmd=`@SIPX_BINDIR@/sipx-config --java`
   Dependencies=`@SIPX_BINDIR@/java-dep -d @SIPX_JAVADIR@/sipXcommons @provision_PKGS@`
@@ -56,34 +45,61 @@ start() {
   Command="$JavaCmd \
     -Dprocname=sipxprovision \
     $TrustStoreOpts \
-	$KeyStoreOpts \
+    $KeyStoreOpts \
     ${SIPXPROVISION_OPTS} \
     -Djetty.x509.algorithm=$X509Algorithm \
-	-Djetty.ssl.password=$StorePassword \
-	-Djetty.ssl.keypassword=$StorePassword	\
+    -Djetty.ssl.password=$StorePassword \
+    -Djetty.ssl.keypassword=$StorePassword \
     -Dconf.dir=@SIPX_CONFDIR@ \
     -Dvar.dir=@SIPX_VARDIR@ \
     org.sipfoundry.sipxprovision.SipXprovision \
     $Args"
   if [ -n "${NoFork}" ] ; then
+    killAnyOrphans @SIPXPBXUSER@ $regex
     runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}"
   else
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+
     echo -n $"Starting $prog: "
     runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}" >/dev/null 2>&1 &
     echo $! > ${pidfile}
-    echo_success
-  fi  
+
+    if [ $# -gt 0 ]; then
+      #check if process was spawned
+      checkRunningInstanceTimeout @SIPXPBXUSER@ $regex
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+      pid=`ps -u @SIPXPBXUSER@ -o pid,args | grep $regex | grep -v "grep" | awk '{print $1 }'`
+      checkIfListening $pid
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; echo; }
+    else
+      echo_success; echo;
+    fi
+  fi
 }
 
 stop() {
-  echo -n $"Stopping sipxprovision: "
-  killproc -p "${pidfile}" "sipxprovision"
+  echo -n $"Stopping $prog: "
+  killAnyOrphans @SIPXPBXUSER@ $regex
+  checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
   Status=$?
-  echo
-  [ $Status -eq 0 ] && rm -f "${pidfile}"
+  [ $Status -eq 0 ] && { echo_failure; echo; exit $ERUNNING; }
+  [ $Status -eq 0 ] || { echo_success; echo; }
 }
 
 restart() {
+  stop
+  # sleep for no good reason. Can be disconcerting if stop/start
+  # switch is too fast IMHO
+  sleep 1
+  start $withCheck
+}
+
+asyncrestart() {
   stop
   # sleep for no good reason. Can be disconcerting if stop/start
   # switch is too fast IMHO
@@ -97,7 +113,7 @@ case "$1" in
     start
     ;;
   start)
-    start
+    start $withCheck
     ;;
   stop)
     stop
@@ -105,18 +121,24 @@ case "$1" in
   restart|reload|force-reload)
     restart
     ;;
+  asyncrestart)
+    asyncrestart
+    ;;
   condrestart)
-    [ -f ${pidfile} ] && restart || :
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p ${pidfile} sipxprovision
+    checkRunningInstance @SIPXPBXUSER@ $regex $prog
+    Status=$?
     ;;
   configtest)
     configtest
     ;;
   *)
-    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|nofork}"
-    Status=1
+    echo "Usage: $0 {start|stop|status|restart|asyncrestart|reload|force-reload|condrestart|nofork}"
+    Status=$EINCORRECTUSAGE
 esac
 
 exit $Status
diff --git a/sipXregistry/bin/sipxregistrar.in b/sipXregistry/bin/sipxregistrar.in
--- a/sipXregistry/bin/sipxregistrar.in
+++ b/sipXregistry/bin/sipxregistrar.in
@@ -14,8 +14,8 @@
 # Contributors retain copyright to elements licensed under a Contributor Agreement.
 # Licensed to the User under the LGPL license.
 
-. /etc/rc.d/init.d/functions || exit 1
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || exit 1
+. /etc/rc.d/init.d/functions || exit $ENOENT
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
 
 prog=sipregistrar
 exec="@SIPX_BINDIR@/${prog}"
@@ -25,27 +25,51 @@ pidfile="@SIPX_RUNDIR@/sipxregistrar.pid"
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
 
 start() {
-    [ -x $exec ] || exit 5
-    [ -f $config ] || exit 6
-    if [ -n "${NoFork}" ] ; then
-      runuser - @SIPXPBXUSER@ -c $exec
-    else
-      echo -n $"Starting $prog: "
-      daemon --user @SIPXPBXUSER@ --pidfile $pidfile $exec $pidfile
+  [ -x $exec ] || { echo -n "$execError"; echo_failure; echo; exit $NOEXEC; }
+  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; echo; exit$ENOENT; }
+  if [ -n "${NoFork}" ] ; then
+    killAnyOrphans @SIPXPBXUSER@ $prog
+    runuser - @SIPXPBXUSER@ -c $exec
+  else
+    checkRunningInstance @SIPXPBXUSER@ $prog > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+
+    echo -n $"Starting $prog: "
+    daemon --user @SIPXPBXUSER@ --pidfile $pidfile $exec $pidfile
+    Status=$?
+
+    if [ $# -gt 0 ]; then
+      #check if process spawned
+      checkRunningInstanceTimeout @SIPXPBXUSER@ $prog
       Status=$?
-      echo_success
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+       checkIfListening $prog
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; echo; }
+    else
+      [ $Status -eq 0 ] && { echo_success; echo; }
+      [ $Status -eq 0 ] || { echo_failure; echo; }
     fi
+  fi
 }
 
 stop() {
-  echo -n $"Stopping sipXregistrar: "
-  killproc -p "${pidfile}" "${exec}"
+  echo -n $"Stopping $prog: "
+  killproc "${exec}"
   Status=$?
   echo
   [ $Status -eq 0 ] && rm -f "${pidfile}"
+  killAnyOrphans @SIPXPBXUSER@ $prog
 }
 
 restart() {
+  stop
+  start withCheck
+}
+
+asyncrestart() {
   stop
   start
 }
@@ -115,7 +139,7 @@ case "$1" in
     start
     ;;
   start)
-    start
+    start $withCheck
     ;;
   stop)
     stop
@@ -123,19 +147,24 @@ case "$1" in
   restart|reload|force-reload)
     restart
     ;;
+  asyncrestart)
+    asyncrestart
+    ;;
   condrestart)
-    [ -f ${pidfile} ] && restart || :
+    checkRunningInstance @SIPXPBXUSER@ $prog > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p "${pidfile}" sipxregistrar
+    checkRunningInstance @SIPXPBXUSER@ $prog
     Status=$?
     ;;
   configtest)
     configtest
     ;;
   *)
-    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|nofork}"
-    Status=1
+    echo "Usage: $0 {start|stop|status|restart|asyncrestart|reload|force-reload|condrestart|nofork}"
+    Status=$EINCORRECTUSAGE
 esac
 
 exit $Status
diff --git a/sipXrelay/sipxrelay.in b/sipXrelay/sipxrelay.in
--- a/sipXrelay/sipxrelay.in
+++ b/sipXrelay/sipxrelay.in
@@ -18,61 +18,75 @@
 # FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 # details.
 
-. /etc/rc.d/init.d/functions || exit 1
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || exit 1
+. /etc/rc.d/init.d/functions || exit $ENOENT
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
 
 prog=sipxrelay
 pidfile="@SIPX_RUNDIR@/sipxrelay.pid"
+regex="Dprocname=sipxrelay"
 
 [ -e @SIPX_CONFDIR@/${prog}rc ] && . @SIPX_CONFDIR@/sysconfig/${prog}rc
 
-checkRunningInstance() {
-  if [ -f "${pidfile}" ]; then
-    pid=`cat ${pidfile}`
-    if checkpid $pid 2>&1; then
-      echo "Process $prog is already running with pid $pid"
-      exit 1
+start() {
+  JavaCmd=`@SIPX_BINDIR@/sipx-config --java`
+  Dependencies=`@SIPX_BINDIR@/java-dep -d @SIPX_JAVADIR@/sipXcommons @relay_PKGS@`
+  export CLASSPATH=`echo @SIPX_JAVADIR@/sipXbridge/*.jar ${Dependencies} | sed -e 's/ /:/g'`
+  setJavaSslOpts
+  # procname is there so cfengine can find it
+  Command="$JavaCmd \
+    -Dprocname=sipxrelay \
+    -Dconf.dir=@SIPX_CONFDIR@ \
+    -Dsipxrelay.command=start \
+     $JavaSslOpts \
+    -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger \
+    org.sipfoundry.sipxrelay.SymmitronServer \
+    $Args"
+  if [ -n "${NoFork}" ] ; then
+    killAnyOrphans @SIPXPBXUSER@ $regex
+    runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}"
+  else
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+
+    echo -n $"Starting $prog: "
+    runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}" >/dev/null 2>&1 &
+    echo $! > ${pidfile}
+
+    if [ $# -gt 0 ]; then
+      #check if process was spawned
+      checkRunningInstanceTimeout @SIPXPBXUSER@ $regex
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+      pid=`ps -u @SIPXPBXUSER@ -o pid,args | grep $regex | grep -v "grep" | awk '{print $1 }'`
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; echo; }
+    else
+      echo_success; echo;
     fi
   fi
 }
 
-start() {
-    checkRunningInstance
-    JavaCmd=`@SIPX_BINDIR@/sipx-config --java`
-    Dependencies=`@SIPX_BINDIR@/java-dep -d @SIPX_JAVADIR@/sipXcommons @relay_PKGS@`
-    export CLASSPATH=`echo @SIPX_JAVADIR@/sipXbridge/*.jar ${Dependencies} | sed -e 's/ /:/g'`
-    setJavaSslOpts
-    # procname is there so cfengine can find it
-    Command="$JavaCmd \
-      -Dprocname=sipxrelay \
-      -Dconf.dir=@SIPX_CONFDIR@ \
-      -Dsipxrelay.command=start \
-      $JavaSslOpts \
-      -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger \
-      org.sipfoundry.sipxrelay.SymmitronServer \
-      $Args"
-    if [ -n "${NoFork}" ] ; then
-      runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}"
-    else
-      echo -n $"Starting $prog: "
-      runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}" >/dev/null 2>&1 &
-      echo $! > ${pidfile}
-      echo_success
-    fi
-}
-
 stop() {
-  echo -n $"Stopping sipxrelay: "
-  killproc -p "${pidfile}" -t30 -TERM "sipxrelay"
+  echo -n $"Stopping sipxbridge: "
+  killAnyOrphans @SIPXPBXUSER@ $regex
+  checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
   Status=$?
-  echo
-  [ $Status -eq 0 ] && rm -f "${pidfile}"
+  [ $Status -eq 0 ] && { echo_failure; echo; exit $ERUNNING; }
+  [ $Status -eq 0 ] || { echo_success; echo; }
 }
 
 restart() {
   stop
+  start $withCheck
+}
+
+asyncrestart() {
+  stop
   start
 }
+
 
 configtest() {
   Status=0
@@ -80,7 +94,7 @@ configtest() {
   if [ -e $logfile -a ! -w $logfile ]
   then
      echo "Log file '$logfile' exists but is not writable by user '@SIPXPBXUSER@'." >&2
-     Status=1
+     Status=$ENOTWRITABLE
   fi
   JavaCmd=`@SIPX_BINDIR@/sipx-config --java`
   Dependencies=`@SIPX_BINDIR@/java-dep -d @SIPX_JAVADIR@/sipXcommons @relay_PKGS@`
@@ -103,7 +117,7 @@ case "$1" in
     start
     ;;
   start)
-    start
+    start $withCheck
     ;;
   stop)
     stop
@@ -111,18 +125,24 @@ case "$1" in
   restart|reload|force-reload)
     restart
     ;;
+  asyncrestart)
+    asyncrestart
+    ;;
   condrestart)
-    [ -f ${pidfile} ] && restart || :
+    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p ${pidfile} sipxrelay
+    checkRunningInstance @SIPXPBXUSER@ $regex $prog
+    Status=$?
     ;;
   configtest)
     configtest
     ;;
   *)
-    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|nofork}"
-    Status=1
+    echo "Usage: $0 {start|stop|status|restart|asyncrestart|reload|force-reload|condrestart|nofork}"
+    Status=$EINCORRECTUSAGE
 esac
 
 exit $Status
diff --git a/sipXsqa/bin/sipxsqa.in b/sipXsqa/bin/sipxsqa.in
--- a/sipXsqa/bin/sipxsqa.in
+++ b/sipXsqa/bin/sipxsqa.in
@@ -5,12 +5,12 @@
 # description: sipxsqa is a SIP park for telecommunications
 # processname: sipXsqa
 
-# Copyright (C) 2007 Pingtel Corp., certain elements licensed under a Contributor Agreement.  
+# Copyright (C) 2007 Pingtel Corp., certain elements licensed under a Contributor Agreement.
 # Contributors retain copyright to elements licensed under a Contributor Agreement.
 # Licensed to the User under the LGPL license.
 
-. /etc/rc.d/init.d/functions || exit 1
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || exit 1
+. /etc/rc.d/init.d/functions || exit $ENOENT
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
 
 prog=sipxsqa
 exec="@SIPX_BINDIR@/${prog}"
@@ -22,34 +22,58 @@ logfile="@SIPX_LOGDIR@/sipxsqa.log"
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
 
 start() {
-    [ -x $exec ] || exit 5
-    [ -f $config ] || exit 6
-    if [ -n "${NoFork}" ] ; then
-      runuser - @SIPXPBXUSER@ -c "$exec  \
-        --config-file $config \
-        --pid-file $pidfile \
-        --log-file $logfile"
-    else
-      echo -n $"Starting $prog: "
-      daemon --user @SIPXPBXUSER@ --pidfile $pidfile $exec \
-        --config-file $config \
-        --pid-file $pidfile \
-        --log-file $logfile \
-        --daemonize
+  [ -x $exec ] || { echo -n "$execError"; echo_failure; echo; exit $ENOEXEC; }
+  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; echo; exit $ENOENT; }
+  if [ -n "${NoFork}" ] ; then
+    killAnyOrphans @SIPXPBXUSER@ $prog
+    runuser - @SIPXPBXUSER@ -c "$exec  \
+      --config-file $config \
+      --pid-file $pidfile \
+      --log-file $logfile"
+  else
+    checkRunningInstance @SIPXPBXUSER@ $prog > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+
+    echo -n $"Starting $prog: "
+    daemon --user @SIPXPBXUSER@ --pidfile $pidfile $exec \
+      --config-file $config \
+      --pid-file $pidfile \
+      --log-file $logfile \
+      --daemonize
+    Status=$?
+
+    if [ $# -gt 0 ]; then
+      #check if process was spawned
+      checkRunningInstanceTimeout @SIPXPBXUSER@ $prog
       Status=$?
-      echo_success
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+      checkIfListening $prog
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; echo; }
+    else
+      [ $Status -eq 0 ] && { echo_success; echo; }
+      [ $Status -eq 0 ] || { echo_success; failure; }
     fi
+  fi
 }
 
 stop() {
-  echo -n $"Stopping sipXsqa: "
-  killproc -p "${pidfile}" "${binfile}"
+  echo -n $"Stopping $prog: "
+  killproc "${prog}"
   Status=$?
   echo
   [ $Status -eq 0 ] && rm -f "${pidfile}"
+  killAnyOrphans @SIPXPBXUSER@ $prog
 }
 
 restart() {
+  stop
+  start $withCheck
+}
+
+asyncrestart() {
   stop
   start
 }
@@ -68,7 +92,7 @@ case "$1" in
     start
     ;;
   start)
-    start
+    start $withCheck
     ;;
   stop)
     stop
@@ -76,19 +100,24 @@ case "$1" in
   restart|reload|force-reload)
     restart
     ;;
+  asyncrestart)
+    asyncrestart
+    ;;
   condrestart)
-    [ -f ${pidfile} ] && restart || :
+    checkRunningInstance @SIPXPBXUSER@ $prog > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p "${pidfile}" "${prog}"
+    checkRunningInstance @SIPXPBXUSER@ $prog
     Status=$?
     ;;
   configtest)
     configtest
     ;;
   *)
-    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|nofork}"
-    Status=1
+    echo "Usage: $0 {start|stop|status|restart|asyncrestart|reload|force-reload|condrestart|nofork}"
+    Status=$EINCORRECTUSAGE
 esac
 
 exit $Status
diff --git a/sipXsupervisor/bin/sipxsupervisor.in b/sipXsupervisor/bin/sipxsupervisor.in
--- a/sipXsupervisor/bin/sipxsupervisor.in
+++ b/sipXsupervisor/bin/sipxsupervisor.in
@@ -11,10 +11,12 @@
 
 # Source function library.
 . /etc/init.d/functions
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
 
 config="@SIPX_CFINPUTS@/sipxsupervisord.cf"
 exec="/usr/sbin/cf-serverd"
 prog=$(basename $exec)
+progName="cf-serverd"
 # used to tell which config is in use.
 configid=/var/run/sipxsupervisor-configid
 
@@ -24,71 +26,107 @@ lockfile=/var/lock/subsys/$prog
 sipxagentlockfile="@SIPX_RUNDIR@/sipxagent.lock"
 
 start() {
-	echo -n $config > $configid
-	echo -n $"Starting sipxsupervisor: "
-	daemon $exec -f $config
-	RETVAL=$?
-	echo
-	[ $RETVAL -eq 0 ] && touch $lockfile
+  [ -x $exec ] || { echo -n "$execError"; echo_failure; echo; exit $ENOEXEC; }
+  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; echo; exit $ENOENT; }
+  checkRunningInstance "root" $prog > /dev/null
+  Status=$?
+  [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
 
-	#if sipxagent is not running make sure the host is pulling the last configuration on startup.
-    #this applies in cases when secondary host starts after master, and master changed configuration
-    #while the secondary is down. sipxagent has to be run as root because we don't want to go through
-    #supervisor again
-	if [ ! -f $sipxagentlockfile ]
-	then
-		runuser - root -s @SIPX_BINDIR@/sipxagent
-	fi		
+  echo -n $config > $configid
+  echo -n $"Starting $progName: "
+  daemon $exec -f $config
+  Status=$?
+  [ $Status -eq 0 ] && touch $lockfile
 
-	return $RETVAL
+  if [ $# -gt 0 ]; then
+    checkRunningInstanceTimeout "root" $prog $maxTimeout
+    Status=$?
+    [ $Status -eq $ESRCH ] && { echo_failure; echo; exit $ESRCH; }
+
+    #sipxagent running
+    if [ -f @sipxagentlockfile ]; then
+      checkIfListening $progName
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; echo; return $Status; }
+    fi
+  fi
+
+  #if sipxagent is not running make sure the host is pulling the last configuration on startup.
+  #this applies in cases when secondary host starts after master, and master changed configuration
+  #while the secondary is down. sipxagent has to be run as root because we don't want to go through
+  #supervisor again
+  if [ ! -f $sipxagentlockfile ]; then
+    runuser - root -s @SIPX_BINDIR@/sipxagent
+
+    if [ $# -gt 0 ]; then
+      checkIfListening $prog
+      Status=$?
+      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; echo; return 0; }
+    fi
+  fi
+
 }
 
 nofork() {
-	$exec -v -f $config
+  $exec -v -f $config
 }
 
 stop() {
-	echo -n $"Stopping sipxsupervisor: "
-	killproc $prog
-	RETVAL=$?
-	echo
-	[ $RETVAL -eq 0 ] && rm -f $lockfile
-	return $RETVAL
+  echo -n $"Stopping $progName: "
+  killproc $prog
+  RETVAL=$?
+  echo
+  [ $RETVAL -eq 0 ] && rm -f $lockfile
+  killAnyOrphans "root" $prog
+  return $RETVAL
 }
 
 restart() {
-  	stop
-	start
+  stop
+  start $withCheck
+}
+
+asyncrestart() {
+  stop
+  start
+}
+
+restart() {
+  stop
+  start
 }
 
 reload() {
-    restart
+  restart
 }
 
 force_reload() {
-    restart
-}
-
-fdrstatus() {
-	status $prog
+  restart
 }
 
 case "$1" in
-    start|stop|restart|reload|nofork)
-	$1
-	;;    
-    force-reload)
-        force_reload
-        ;;
-    status)
-  	fdrstatus
-	;;
-    # condrestart - only restarts if service *is* running
-    condrestart)
-        [ ! -f $lockfile ] || restart
-        ;;
-    *)
-        echo $"Usage: $0 {start|stop|status|restart|condrestart|condstart|reload|force-reload|nofork}"
-        exit 3
+  start)
+    start $withCheck
+    ;;
+  stop|restart|asyncrestart|reload|nofork)
+    $1
+    ;;
+  force-reload)
+    force_reload
+    ;;
+  status)
+    checkRunningInstance "root" $prog
+    ;;
+  # condrestart - only restarts if service *is* running
+  condrestart)
+    checkRunningInstance "root" $prog > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] || restart
+    ;;
+  *)
+    echo $"Usage: $0 {start|stop|status|restart|asyncrestartcondrestart|condstart|reload|force-reload|nofork}"
+    exit $EINCORRECTUSAGE
 esac
 exit $?
diff --git a/sipXtunnel/tunnel.in b/sipXtunnel/tunnel.in
--- a/sipXtunnel/tunnel.in
+++ b/sipXtunnel/tunnel.in
@@ -4,8 +4,8 @@
 # description: sipxtunnel is encrypted communications service
 # processname: tunnel
 
-. /etc/rc.d/init.d/functions || exit 1
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || exit 1
+. /etc/rc.d/init.d/functions || exit $ENOENT
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || exit $ENOENT
 
 # Copyright (c) 2012 eZuce, Inc. All rights reserved.
 # Contributed to SIPfoundry under a Contributor Agreement
@@ -31,14 +31,41 @@ USAGE
 
 Status=0
 PidFile=@SIPX_RUNDIR@/tunnel-@MODE@.pid
+[ @MODE@ = "server" ] && regex=".*/stunnel\\s.*/tunnel-server.ini"
+[ @MODE@ = "client" ] && regex=".*/stunnel\\s.*/tunnel-client.ini"
 
 start() {
-    echo "Starting tunnel service in @MODE@ mode..."
-    /usr/bin/stunnel @SIPX_CONFDIR@/tunnel-@MODE@.ini
+  checkRunningInstance  "root" $regex > /dev/null
+  [ $? -eq 0 ] && { echo -n "@MODE@ $runningError"; echo_failure; echo; exit $ERUNNING; }
+  echo -n "Starting tunnel service in @MODE@ mode..."
+  /usr/bin/stunnel @SIPX_CONFDIR@/tunnel-@MODE@.ini
+
+  if [ $# -gt 0 ]; then
+    #check if process was spawned
+    checkRunningInstanceTimeout "root" $regex
+    Status=$?
+    [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
+    pid=`ps -u "root" -o pid,args | grep $regex | grep -v "grep" | tail -1 | awk '{print $1 }'`
+    checkIfListening $pid
+    Status=$?
+    [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
+    [ $Status -eq 0 ] && { echo_success; echo; }
+  fi
 }
 
 stop() {
-    sipx_stop tunnel ${PidFile}
+  sipx_stop tunnel ${PidFile}
+  killAnyOrphans root $regex
+}
+
+restart() {
+  stop
+  start $withCheck
+}
+
+asyncrestart() {
+  stop
+  start
 }
 
 case "$1" in
@@ -47,27 +74,32 @@ case "$1" in
     start
     ;;
   start)
-    start
+    start $withCheck
     ;;
   stop)
     stop
     ;;
   restart|reload|force-reload)
-    stop
-    start
+    restart
+    ;;
+  asyncrestart)
+    asyncrestart
     ;;
   condrestart)
-    [ -f ${PidFile} ] && restart || :
+    checkRunningInstance  root $regex > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    status -p ${PidFile} tunnel-@MODE@
+    checkRunningInstance root $regex tunnel-@MODE@
+    Status=$?
     ;;
   configtest)
     configtest
     ;;
   *)
     usage
-    Status=1
+    Status=$EINCORRECTUSAGE
 esac
 
 exit $Status
